// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.NSPRFP401.Request</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.NSPRFP401.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


   

    public partial class Utility
    {
        public static Utility Create(string toid,string fromid,string orderkey,string sku,string qty,string userid)
        {
            Utility data = new Utility();
            data.UtilityHeader.toid = toid;
            data.UtilityHeader.fromid = fromid;
            data.UtilityHeader.orderkey = orderkey;
            data.UtilityHeader.sku = sku;
            data.UtilityHeader.qty = qty;
            data.UtilityHeader.userid = userid;
            return data;
        }
        private UtilityHeader utilityHeaderField;

        public UtilityHeader UtilityHeader
        {
            get
            {
                if ((this.utilityHeaderField == null))
                {
                    this.utilityHeaderField = new UtilityHeader();
                }
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }
    }

    public partial class UtilityHeader
    {

        private string procNameField;

        private string sendDelimiterField;

        private string ptcidField;

        private string useridField;

        private string taskIdField;

        private string databasenameField;

        private string appflagField;

        private string recordTypeField;

        private string serverField;

        private string toidField;

        private string orderkeyField;

        private string fromidField;

        private string skuField;

        private string lotField;

        private string qtyField;

        private string pckprinterid1Field;

        private string pckcopies1Field;

        private string pckprinterid2Field;

        private string pckcopies2Field;

        private string pckprinterid3Field;

        private string pckcopies3Field;

        private string pckprinterid4Field;

        private string pckcopies4Field;

        private string pckprinterid5Field;

        private string pckcopies5Field;

        private string pckprinterid6Field;

        private string pckcopies6Field;

        private string cartontypeField;

        private string transactionkeyField;

        public UtilityHeader()
        {
            this.procNameField = "NSPRFP401";
            this.sendDelimiterField = "`";
            this.ptcidField = "";
            this.useridField = "";
            this.taskIdField = "";
            this.databasenameField = "";
            this.appflagField = "";
            this.recordTypeField = "";
            this.serverField = "";
            this.qtyField = "0";
            this.lotField = "";
            this.pckprinterid1Field = "P01";
            this.pckcopies1Field = "1";
            this.pckprinterid2Field = "P01";
            this.pckcopies2Field = "1";
            this.pckprinterid3Field = "P01";
            this.pckcopies3Field = "1";
            this.pckprinterid4Field = "P01";
            this.pckcopies4Field = "1";
            this.pckprinterid5Field = "P01";
            this.pckcopies5Field = "1";
            this.pckprinterid6Field = "P01";
            this.pckcopies6Field = "1";
            this.cartontypeField = "";
            this.transactionkeyField = "";
        }

        public string ProcName
        {
            get
            {
                return this.procNameField;
            }
            set
            {
                this.procNameField = value;
            }
        }

        public string sendDelimiter
        {
            get
            {
                return this.sendDelimiterField;
            }
            set
            {
                this.sendDelimiterField = value;
            }
        }

        public string ptcid
        {
            get
            {
                return this.ptcidField;
            }
            set
            {
                this.ptcidField = value;
            }
        }

        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }

        public string taskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }

        public string databasename
        {
            get
            {
                return this.databasenameField;
            }
            set
            {
                this.databasenameField = value;
            }
        }

        public string appflag
        {
            get
            {
                return this.appflagField;
            }
            set
            {
                this.appflagField = value;
            }
        }

        public string recordType
        {
            get
            {
                return this.recordTypeField;
            }
            set
            {
                this.recordTypeField = value;
            }
        }

        public string server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }

        public string toid
        {
            get
            {
                return this.toidField;
            }
            set
            {
                this.toidField = value;
            }
        }

        public string orderkey
        {
            get
            {
                return this.orderkeyField;
            }
            set
            {
                this.orderkeyField = value;
            }
        }

        public string fromid
        {
            get
            {
                return this.fromidField;
            }
            set
            {
                this.fromidField = value;
            }
        }

        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }

        public string lot
        {
            get
            {
                return this.lotField;
            }
            set
            {
                this.lotField = value;
            }
        }

        public string qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        public string pckprinterid1
        {
            get
            {
                return this.pckprinterid1Field;
            }
            set
            {
                this.pckprinterid1Field = value;
            }
        }

        public string pckcopies1
        {
            get
            {
                return this.pckcopies1Field;
            }
            set
            {
                this.pckcopies1Field = value;
            }
        }

        public string pckprinterid2
        {
            get
            {
                return this.pckprinterid2Field;
            }
            set
            {
                this.pckprinterid2Field = value;
            }
        }

        public string pckcopies2
        {
            get
            {
                return this.pckcopies2Field;
            }
            set
            {
                this.pckcopies2Field = value;
            }
        }

        public string pckprinterid3
        {
            get
            {
                return this.pckprinterid3Field;
            }
            set
            {
                this.pckprinterid3Field = value;
            }
        }

        public string pckcopies3
        {
            get
            {
                return this.pckcopies3Field;
            }
            set
            {
                this.pckcopies3Field = value;
            }
        }

        public string pckprinterid4
        {
            get
            {
                return this.pckprinterid4Field;
            }
            set
            {
                this.pckprinterid4Field = value;
            }
        }

        public string pckcopies4
        {
            get
            {
                return this.pckcopies4Field;
            }
            set
            {
                this.pckcopies4Field = value;
            }
        }

        public string pckprinterid5
        {
            get
            {
                return this.pckprinterid5Field;
            }
            set
            {
                this.pckprinterid5Field = value;
            }
        }

        public string pckcopies5
        {
            get
            {
                return this.pckcopies5Field;
            }
            set
            {
                this.pckcopies5Field = value;
            }
        }

        public string pckprinterid6
        {
            get
            {
                return this.pckprinterid6Field;
            }
            set
            {
                this.pckprinterid6Field = value;
            }
        }

        public string pckcopies6
        {
            get
            {
                return this.pckcopies6Field;
            }
            set
            {
                this.pckcopies6Field = value;
            }
        }

        public string cartontype
        {
            get
            {
                return this.cartontypeField;
            }
            set
            {
                this.cartontypeField = value;
            }
        }

        public string transactionkey
        {
            get
            {
                return this.transactionkeyField;
            }
            set
            {
                this.transactionkeyField = value;
            }
        }
    }
}
