// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.Arrival01.Request</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.Arrival01.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


   

    public partial class AdvancedShipNotice
    {

        private AdvancedShipNoticeHeader advancedShipNoticeHeaderField;

        public AdvancedShipNoticeHeader AdvancedShipNoticeHeader
        {
            get
            {
                if ((this.advancedShipNoticeHeaderField == null))
                {
                    this.advancedShipNoticeHeaderField = new AdvancedShipNoticeHeader();
                }
                return this.advancedShipNoticeHeaderField;
            }
            set
            {
                this.advancedShipNoticeHeaderField = value;
            }
        }
    }

    public partial class AdvancedShipNoticeHeader
    {
        public AdvancedShipNoticeHeader()
        {
            //this.performanceData24Field = "0";
        }
        private string dischargestatusField;

       
        private string thepalletField;

        
        private string thecaseField;

       
        private string storerKeyField;

        private string receiptKeyField;

        private string doorsKeyField;

        private string pierField;
        private string pqcstatusField;
        private string thecubeField;
        private string arrangestatusField;





        private string performanceData15Field;
        private string performanceData24Field;

        

        private List<AdvancedShipNoticeDetail> advancedShipNoticeDetailField;

        public string StorerKey
        {
            get
            {
                return this.storerKeyField;
            }
            set
            {
                this.storerKeyField = value;
            }
        }

        public string ReceiptKey
        {
            get
            {
                return this.receiptKeyField;
            }
            set
            {
                this.receiptKeyField = value;
            }
        }

        public string DoorsKey
        {
            get
            {
                return this.doorsKeyField;
            }
            set
            {
                this.doorsKeyField = value;
            }
        }

        public string Pier
        {
            get
            {
                return this.pierField;
            }
            set
            {
                this.pierField = value;
            }
        }
        public string PerformanceData15
        {
            get
            {
                return this.performanceData15Field;
            }
            set
            {
                this.performanceData15Field = value;
            }
        }
        public string PerformanceData24
        {
            get
            {
                return this.performanceData24Field;
            }
            set
            {
                this.performanceData24Field = value;
            }
        }
        public string DischargeStatus
        {
            get { return dischargestatusField; }
            set { dischargestatusField = value; }
        }
        public string ThePallet
        {
            get { return thepalletField; }
            set { thepalletField = value; }
        }
        public string TheCase
        {
            get { return thecaseField; }
            set { thecaseField = value; }
        }

        public string PqcStatus
        {
            get
            {
                return this.pqcstatusField;
            }
            set
            {
                this.pqcstatusField = value;
            }
        }
        public string TheCube
        {
            get { return thecubeField; }
            set { thecubeField = value; }
        }
        public string ArrangeStatus
        {
            get { return arrangestatusField; }
            set { arrangestatusField = value; }
        }

        [System.Xml.Serialization.XmlElement("AdvancedShipNoticeDetail")]
        public List<AdvancedShipNoticeDetail> AdvancedShipNoticeDetail
        {
            get
            {
                if ((this.advancedShipNoticeDetailField == null))
                {
                    this.advancedShipNoticeDetailField = new List<AdvancedShipNoticeDetail>();
                }
                return this.advancedShipNoticeDetailField;
            }
            set
            {
                this.advancedShipNoticeDetailField = value;
            }
        }
    }


    public partial class AdvancedShipNoticeDetail
    {
        private string receiptKeyField;

        private string receiptLineNumberField;

        private string pqcqtyinspectedField;

        private string pqcqtyrejectedField;

        private string pqcstatusfield;

        private string pqcpeoplenumField;
        private string pqcwhoField;

        
        public string ReceiptKey
        {
            get
            {
                return this.receiptKeyField;
            }
            set
            {
                this.receiptKeyField = value;
            }
        }

        public string ReceiptLineNumber
        {
            get
            {
                return this.receiptLineNumberField;
            }
            set
            {
                this.receiptLineNumberField = value;
            }
        }

        public string PqcQtyInspected
        {
            get
            {
                return this.pqcqtyinspectedField;
            }
            set
            {
                this.pqcqtyinspectedField = value;
            }
        }

        public string PqcQtyRejected
        {
            get
            {
                return this.pqcqtyrejectedField;
            }
            set
            {
                this.pqcqtyrejectedField = value;
            }
        }
        public string PqcStatus
        {
            get
            {
                return this.pqcstatusfield;
            }
            set
            {
                this.pqcstatusfield = value;
            }
        }

        public string PqcPeopleNum
        {
            get
            {
                return this.pqcpeoplenumField;
            }
            set
            {
                this.pqcpeoplenumField = value;
            }
        }
        public string PqcWho
        {
            get { return pqcwhoField; }
            set { pqcwhoField = value; }
        }
    }
}
