// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.Arrival01.Request</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.asnlist01.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


   

    public partial class AdvancedShipNotice
    {

        public static AdvancedShipNotice Create(string pier)
        {
            AdvancedShipNotice data = new AdvancedShipNotice();
            data.AdvancedShipNoticeHeader = new AdvancedShipNoticeHeader();
            data.AdvancedShipNoticeHeader.Pier = pier;
            data.AdvancedShipNoticeHeader.Status = "0,101,102";
            return data;
        }
        public static AdvancedShipNotice CreateByReceiptKey(string receiptkey)
        {
            AdvancedShipNotice data = new AdvancedShipNotice();
            data.AdvancedShipNoticeHeader = new AdvancedShipNoticeHeader();
            data.AdvancedShipNoticeHeader.ReceiptKey = receiptkey;
            data.AdvancedShipNoticeHeader.Status = "0,101,102,103,104,106";
            return data;
        }
        public static AdvancedShipNotice CreateByReceiptKeyPQC(string receiptkey)
        {
            AdvancedShipNotice data = new AdvancedShipNotice();
            data.AdvancedShipNoticeHeader = new AdvancedShipNoticeHeader();
            data.AdvancedShipNoticeHeader.ReceiptKey = receiptkey;
            data.AdvancedShipNoticeHeader.Status = "0,5,101,102,103,104,105,106";
            return data;
        }
        public static AdvancedShipNotice CreateByReceiptKey(string receiptkey,string status)
        {
            AdvancedShipNotice data = new AdvancedShipNotice();
            data.AdvancedShipNoticeHeader = new AdvancedShipNoticeHeader();
            data.AdvancedShipNoticeHeader.ReceiptKey = receiptkey;
            data.AdvancedShipNoticeHeader.Status = status;
            return data;
        }

        private AdvancedShipNoticeHeader advancedShipNoticeHeaderField;

        public AdvancedShipNoticeHeader AdvancedShipNoticeHeader
        {
            get
            {
                if ((this.advancedShipNoticeHeaderField == null))
                {
                    this.advancedShipNoticeHeaderField = new AdvancedShipNoticeHeader();
                }
                return this.advancedShipNoticeHeaderField;
            }
            set
            {
                this.advancedShipNoticeHeaderField = value;
            }
        }
    }

    public partial class AdvancedShipNoticeHeader
    {

        private string serialkeyField;


        public string SerialKey
        {
            get { return serialkeyField; }
            set { serialkeyField = value; }
        }

        private string receiptkeyField;

        public string ReceiptKey
        {
            get { return receiptkeyField; }
            set { receiptkeyField = value; }
        }
        private string statusField;

        public string Status
        {
            get { return statusField; }
            set { statusField = value; }
        }

        private string pierField;


        public string Pier
        {
            get
            {
                return this.pierField;
            }
            set
            {
                this.pierField = value;
            }
        }

        private string dischargestatusField;
        public string DischargeStatus
        {
            get { return dischargestatusField; }
            set { dischargestatusField = value; }
        }


    }
}
