// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.DM01.Request</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.DM01.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;

 

    public partial class DoorsManagement
    {
        public static DoorsManagement CreateByParkNum(string parknum)
        {
            DoorsManagement data = new DoorsManagement();
            data.DoorsManagementHeader = new DoorsManagementHeader();

            data.DoorsManagementHeader.ParkNum = parknum;
            return data;
        }
        private DoorsManagementHeader doorsManagementHeaderField;

        public DoorsManagementHeader DoorsManagementHeader
        {
            get
            {
                if ((this.doorsManagementHeaderField == null))
                {
                    this.doorsManagementHeaderField = new DoorsManagementHeader();
                }
                return this.doorsManagementHeaderField;
            }
            set
            {
                this.doorsManagementHeaderField = value;
            }
        }
    }

    public partial class DoorsManagementHeader
    {

        private string ParkNumField;

        private string statusField;

        public DoorsManagementHeader()
        {
            this.statusField = "0,2,3";
        }

        public string ParkNum
        {
            get
            {
                return this.ParkNumField;
            }
            set
            {
                this.ParkNumField = value;
            }
        }

        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
}
