// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.DM01.Response</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.DM01.Response
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class DoorsManagement
    {

        private List<DoorsManagementHeader> doorsManagementHeaderField;

        public DoorsManagement()
        {
            this.doorsManagementHeaderField = new List<DoorsManagementHeader>();
        }
        [System.Xml.Serialization.XmlElement("DoorsManagementHeader")]
        public List<DoorsManagementHeader> DoorsManagementHeader
        {
            get
            {
                return this.doorsManagementHeaderField;
            }
            set
            {
                this.doorsManagementHeaderField = value;
            }
        }
    }

    public partial class DoorsManagementHeader
    {

        private   string serialKeyField;

        private string whseIdField;

        private   string dOORSKEYField;

        private string dRIVERCOMPANYField;

        private   string dRIVERPHONEField;

        private string driverNameField;

        private string pLATENUMBERField;

        private   string pARKNUMField;

        private   string iOGOODSField;

        private   string statusField;

        private string addWhoField;

        private string addDateField;

        private string editWhoField;

        private string editDateField;

        private List<DoorsManagementDetail> doorsManagementDetailField;

        public DoorsManagementHeader()
        {
            this.doorsManagementDetailField = new List<DoorsManagementDetail>();
        }

        public   string SerialKey
        {
            get
            {
                return this.serialKeyField;
            }
            set
            {
                this.serialKeyField = value;
            }
        }

        public string WhseId
        {
            get
            {
                return this.whseIdField;
            }
            set
            {
                this.whseIdField = value;
            }
        }

        public   string DOORSKEY
        {
            get
            {
                return this.dOORSKEYField;
            }
            set
            {
                this.dOORSKEYField = value;
            }
        }

        public string DRIVERCOMPANY
        {
            get
            {
                return this.dRIVERCOMPANYField;
            }
            set
            {
                this.dRIVERCOMPANYField = value;
            }
        }

        public   string DRIVERPHONE
        {
            get
            {
                return this.dRIVERPHONEField;
            }
            set
            {
                this.dRIVERPHONEField = value;
            }
        }

        public string DriverName
        {
            get
            {
                return this.driverNameField;
            }
            set
            {
                this.driverNameField = value;
            }
        }

        public string PLATENUMBER
        {
            get
            {
                return this.pLATENUMBERField;
            }
            set
            {
                this.pLATENUMBERField = value;
            }
        }

        public   string PARKNUM
        {
            get
            {
                return this.pARKNUMField;
            }
            set
            {
                this.pARKNUMField = value;
            }
        }

        public   string IOGOODS
        {
            get
            {
                return this.iOGOODSField;
            }
            set
            {
                this.iOGOODSField = value;
            }
        }

        public   string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public string AddWho
        {
            get
            {
                return this.addWhoField;
            }
            set
            {
                this.addWhoField = value;
            }
        }

        public string AddDate
        {
            get
            {
                return this.addDateField;
            }
            set
            {
                this.addDateField = value;
            }
        }

        public string EditWho
        {
            get
            {
                return this.editWhoField;
            }
            set
            {
                this.editWhoField = value;
            }
        }

        public string EditDate
        {
            get
            {
                return this.editDateField;
            }
            set
            {
                this.editDateField = value;
            }
        }
        [System.Xml.Serialization.XmlElement("DoorsManagementDetail")]
        public List<DoorsManagementDetail> DoorsManagementDetail
        {
            get
            {
                return this.doorsManagementDetailField;
            }
            set
            {
                this.doorsManagementDetailField = value;
            }
        }
    }

    public partial class DoorsManagementDetail
    {

        private   string serialKeyField;

        private   string dOORSKEYField;

        private   string dOORSLINENUMBERField;

        private   string pIERField;

        private   string pARKNUMField;

        private   string statusField;

        private string addDateField;

        private string addWhoField;

        private string editDateField;

        private string editWhoField;

        public   string SerialKey
        {
            get
            {
                return this.serialKeyField;
            }
            set
            {
                this.serialKeyField = value;
            }
        }

        public   string DOORSKEY
        {
            get
            {
                return this.dOORSKEYField;
            }
            set
            {
                this.dOORSKEYField = value;
            }
        }

        public   string DOORSLINENUMBER
        {
            get
            {
                return this.dOORSLINENUMBERField;
            }
            set
            {
                this.dOORSLINENUMBERField = value;
            }
        }

        public   string PIER
        {
            get
            {
                return this.pIERField;
            }
            set
            {
                this.pIERField = value;
            }
        }

        public   string PARKNUM
        {
            get
            {
                return this.pARKNUMField;
            }
            set
            {
                this.pARKNUMField = value;
            }
        }

        public   string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public string AddDate
        {
            get
            {
                return this.addDateField;
            }
            set
            {
                this.addDateField = value;
            }
        }

        public string AddWho
        {
            get
            {
                return this.addWhoField;
            }
            set
            {
                this.addWhoField = value;
            }
        }

        public string EditDate
        {
            get
            {
                return this.editDateField;
            }
            set
            {
                this.editDateField = value;
            }
        }

        public string EditWho
        {
            get
            {
                return this.editWhoField;
            }
            set
            {
                this.editWhoField = value;
            }
        }
    }
}
