// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.DM02.Request</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.DM02.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    

    public partial class DoorsManagement
    {

        private DoorsManagementHeader doorsManagementHeaderField;

        public DoorsManagementHeader DoorsManagementHeader
        {
            get
            {
                if ((this.doorsManagementHeaderField == null))
                {
                    this.doorsManagementHeaderField = new DoorsManagementHeader();
                }
                return this.doorsManagementHeaderField;
            }
            set
            {
                this.doorsManagementHeaderField = value;
            }
        }
    }

    public partial class DoorsManagementHeader
    {

        private string serialKeyField;

        private string whseIdField;

        private string doorsKeyField;

        private string driverCompanyField;

        private string driverPhoneField;

        private string driverNameField;

        private string plateNumberField;

        private string parkNumField;

        private string iOGoodsField;

        private string statusField;

        private string addWhoField;

        private string editWhoField;

        private List<DoorsManagementDetail> doorsManagementDetailField;

        public string SerialKey
        {
            get
            {
                return this.serialKeyField;
            }
            set
            {
                this.serialKeyField = value;
            }
        }

        public string WhseId
        {
            get
            {
                return this.whseIdField;
            }
            set
            {
                this.whseIdField = value;
            }
        }

        public string DoorsKey
        {
            get
            {
                return this.doorsKeyField;
            }
            set
            {
                this.doorsKeyField = value;
            }
        }

        public string DriverCompany
        {
            get
            {
                return this.driverCompanyField;
            }
            set
            {
                this.driverCompanyField = value;
            }
        }

        public string DriverPhone
        {
            get
            {
                return this.driverPhoneField;
            }
            set
            {
                this.driverPhoneField = value;
            }
        }

        public string DriverName
        {
            get
            {
                return this.driverNameField;
            }
            set
            {
                this.driverNameField = value;
            }
        }

        public string PlateNumber
        {
            get
            {
                return this.plateNumberField;
            }
            set
            {
                this.plateNumberField = value;
            }
        }

        public string ParkNum
        {
            get
            {
                return this.parkNumField;
            }
            set
            {
                this.parkNumField = value;
            }
        }

        public string IOGoods
        {
            get
            {
                return this.iOGoodsField;
            }
            set
            {
                this.iOGoodsField = value;
            }
        }

        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public string AddWho
        {
            get
            {
                return this.addWhoField;
            }
            set
            {
                this.addWhoField = value;
            }
        }

        public string EditWho
        {
            get
            {
                return this.editWhoField;
            }
            set
            {
                this.editWhoField = value;
            }
        }
        [System.Xml.Serialization.XmlElement("DoorsManagementDetail")]
        public List<DoorsManagementDetail> DoorsManagementDetail
        {
            get
            {
                if ((this.doorsManagementDetailField == null))
                {
                    this.doorsManagementDetailField = new List<DoorsManagementDetail>();
                }
                return this.doorsManagementDetailField;
            }
            set
            {
                this.doorsManagementDetailField = value;
            }
        }
    }

    public partial class DoorsManagementDetail
    {

        private string serialKeyField;

        private string whseIdField;

        private string doorsKeyField;

        private string doorsLineNumberField;

        private string pierField;

        private string parkNumField;

        private string statusField;

        private string addWhoField;

        private string editWhoField;

        public string SerialKey
        {
            get
            {
                return this.serialKeyField;
            }
            set
            {
                this.serialKeyField = value;
            }
        }

        public string WhseId
        {
            get
            {
                return this.whseIdField;
            }
            set
            {
                this.whseIdField = value;
            }
        }

        public string DoorsKey
        {
            get
            {
                return this.doorsKeyField;
            }
            set
            {
                this.doorsKeyField = value;
            }
        }

        public string DoorsLineNumber
        {
            get
            {
                return this.doorsLineNumberField;
            }
            set
            {
                this.doorsLineNumberField = value;
            }
        }

        public string Pier
        {
            get
            {
                return this.pierField;
            }
            set
            {
                this.pierField = value;
            }
        }

        public string ParkNum
        {
            get
            {
                return this.parkNumField;
            }
            set
            {
                this.parkNumField = value;
            }
        }

        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public string AddWho
        {
            get
            {
                return this.addWhoField;
            }
            set
            {
                this.addWhoField = value;
            }
        }

        public string EditWho
        {
            get
            {
                return this.editWhoField;
            }
            set
            {
                this.editWhoField = value;
            }
        }
    }
}
