// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.NSPRFTM01.Response</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.NSPRFIQ01.Response
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Utility
    {

        private List<UtilityHeader> utilityHeaderFields;
        public Utility()
        {
            utilityHeaderFields = new List<UtilityHeader>();
        }
        [System.Xml.Serialization.XmlElement("UtilityHeader")]
        public List<UtilityHeader> UtilityHeaders
        {
            get
            {

                return this.utilityHeaderFields;
            }
            set
            {
                this.utilityHeaderFields = value;
            }
        }
    }

    public partial class UtilityHeader
    {

        private string storerKeyField;

        private string lotField;

        private string skuField;

        private string descrField;

        private string idField;

        private string locField;

        private string qtyField;

        private string lottable01Field;

        private string lottable02Field;

        private string lottable03Field;

        private string lottable04Field;

        private string lottable05Field;

        private string lottable06Field;

        private string lottable07Field;

        private string lottable08Field;

        private string lottable09Field;

        private string lottable10Field;

        private string lOTTABLE11Field;

        private string lOTTABLE12Field;

        private string lOTTABLE13Field;

        private string lOTTABLE14Field;

        private string lOTTABLE15Field;

        private string lOTTABLE16Field;

        private string lOTTABLE17Field;

        private string lOTTABLE18Field;

        private string lOTTABLE19Field;

        private string lOTTABLE20Field;

        private string lOTTABLE21Field;

        private string lOTTABLE22Field;

        private string lOTTABLE23Field;

        private string lOTTABLE24Field;

        private string lOTTABLE25Field;

        private string lOTTABLE26Field;

        private string lOTTABLE27Field;

        private string lOTTABLE28Field;

        private string lOTTABLE29Field;

        private string lOTTABLE30Field;

        private string lOTTABLE31Field;

        private string lOTTABLE32Field;

        private string lOTTABLE33Field;

        private string lOTTABLE34Field;

        private string lOTTABLE35Field;

        private string lOTTABLE36Field;

        private string lOTTABLE37Field;

        private string lOTTABLE38Field;

        private string lOTTABLE39Field;

        private string lOTTABLE40Field;

        private string lOTTABLE41Field;

        private string lOTTABLE42Field;

        private string lOTTABLE43Field;

        private string lOTTABLE44Field;

        private string lOTTABLE45Field;

        private string lOTTABLE46Field;

        private string lOTTABLE47Field;

        private string statusField;

        private string errmsgField;

        private string rectypeField;

        private string rectotalField;

        private string dateFormateField;

        public string StorerKey
        {
            get
            {
                return this.storerKeyField;
            }
            set
            {
                this.storerKeyField = value;
            }
        }

        public string Lot
        {
            get
            {
                return this.lotField;
            }
            set
            {
                this.lotField = value;
            }
        }

        public string Sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }

        public string Descr
        {
            get
            {
                return this.descrField;
            }
            set
            {
                this.descrField = value;
            }
        }

        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string Loc
        {
            get
            {
                return this.locField;
            }
            set
            {
                this.locField = value;
            }
        }

        public string Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        public string Lottable01
        {
            get
            {
                return this.lottable01Field;
            }
            set
            {
                this.lottable01Field = value;
            }
        }

        public string Lottable02
        {
            get
            {
                return this.lottable02Field;
            }
            set
            {
                this.lottable02Field = value;
            }
        }

        public string Lottable03
        {
            get
            {
                return this.lottable03Field;
            }
            set
            {
                this.lottable03Field = value;
            }
        }

        public string Lottable04
        {
            get
            {
                return this.lottable04Field;
            }
            set
            {
                this.lottable04Field = value;
            }
        }

        public string Lottable05
        {
            get
            {
                return this.lottable05Field;
            }
            set
            {
                this.lottable05Field = value;
            }
        }

        public string Lottable06
        {
            get
            {
                return this.lottable06Field;
            }
            set
            {
                this.lottable06Field = value;
            }
        }

        public string Lottable07
        {
            get
            {
                return this.lottable07Field;
            }
            set
            {
                this.lottable07Field = value;
            }
        }

        public string Lottable08
        {
            get
            {
                return this.lottable08Field;
            }
            set
            {
                this.lottable08Field = value;
            }
        }

        public string Lottable09
        {
            get
            {
                return this.lottable09Field;
            }
            set
            {
                this.lottable09Field = value;
            }
        }

        public string Lottable10
        {
            get
            {
                return this.lottable10Field;
            }
            set
            {
                this.lottable10Field = value;
            }
        }

        public string LOTTABLE11
        {
            get
            {
                return this.lOTTABLE11Field;
            }
            set
            {
                this.lOTTABLE11Field = value;
            }
        }

        public string LOTTABLE12
        {
            get
            {
                return this.lOTTABLE12Field;
            }
            set
            {
                this.lOTTABLE12Field = value;
            }
        }

        public string LOTTABLE13
        {
            get
            {
                return this.lOTTABLE13Field;
            }
            set
            {
                this.lOTTABLE13Field = value;
            }
        }

        public string LOTTABLE14
        {
            get
            {
                return this.lOTTABLE14Field;
            }
            set
            {
                this.lOTTABLE14Field = value;
            }
        }

        public string LOTTABLE15
        {
            get
            {
                return this.lOTTABLE15Field;
            }
            set
            {
                this.lOTTABLE15Field = value;
            }
        }

        public string LOTTABLE16
        {
            get
            {
                return this.lOTTABLE16Field;
            }
            set
            {
                this.lOTTABLE16Field = value;
            }
        }

        public string LOTTABLE17
        {
            get
            {
                return this.lOTTABLE17Field;
            }
            set
            {
                this.lOTTABLE17Field = value;
            }
        }

        public string LOTTABLE18
        {
            get
            {
                return this.lOTTABLE18Field;
            }
            set
            {
                this.lOTTABLE18Field = value;
            }
        }

        public string LOTTABLE19
        {
            get
            {
                return this.lOTTABLE19Field;
            }
            set
            {
                this.lOTTABLE19Field = value;
            }
        }

        public string LOTTABLE20
        {
            get
            {
                return this.lOTTABLE20Field;
            }
            set
            {
                this.lOTTABLE20Field = value;
            }
        }

        public string LOTTABLE21
        {
            get
            {
                return this.lOTTABLE21Field;
            }
            set
            {
                this.lOTTABLE21Field = value;
            }
        }

        public string LOTTABLE22
        {
            get
            {
                return this.lOTTABLE22Field;
            }
            set
            {
                this.lOTTABLE22Field = value;
            }
        }

        public string LOTTABLE23
        {
            get
            {
                return this.lOTTABLE23Field;
            }
            set
            {
                this.lOTTABLE23Field = value;
            }
        }

        public string LOTTABLE24
        {
            get
            {
                return this.lOTTABLE24Field;
            }
            set
            {
                this.lOTTABLE24Field = value;
            }
        }

        public string LOTTABLE25
        {
            get
            {
                return this.lOTTABLE25Field;
            }
            set
            {
                this.lOTTABLE25Field = value;
            }
        }

        public string LOTTABLE26
        {
            get
            {
                return this.lOTTABLE26Field;
            }
            set
            {
                this.lOTTABLE26Field = value;
            }
        }

        public string LOTTABLE27
        {
            get
            {
                return this.lOTTABLE27Field;
            }
            set
            {
                this.lOTTABLE27Field = value;
            }
        }

        public string LOTTABLE28
        {
            get
            {
                return this.lOTTABLE28Field;
            }
            set
            {
                this.lOTTABLE28Field = value;
            }
        }

        public string LOTTABLE29
        {
            get
            {
                return this.lOTTABLE29Field;
            }
            set
            {
                this.lOTTABLE29Field = value;
            }
        }

        public string LOTTABLE30
        {
            get
            {
                return this.lOTTABLE30Field;
            }
            set
            {
                this.lOTTABLE30Field = value;
            }
        }

        public string LOTTABLE31
        {
            get
            {
                return this.lOTTABLE31Field;
            }
            set
            {
                this.lOTTABLE31Field = value;
            }
        }

        public string LOTTABLE32
        {
            get
            {
                return this.lOTTABLE32Field;
            }
            set
            {
                this.lOTTABLE32Field = value;
            }
        }

        public string LOTTABLE33
        {
            get
            {
                return this.lOTTABLE33Field;
            }
            set
            {
                this.lOTTABLE33Field = value;
            }
        }

        public string LOTTABLE34
        {
            get
            {
                return this.lOTTABLE34Field;
            }
            set
            {
                this.lOTTABLE34Field = value;
            }
        }

        public string LOTTABLE35
        {
            get
            {
                return this.lOTTABLE35Field;
            }
            set
            {
                this.lOTTABLE35Field = value;
            }
        }

        public string LOTTABLE36
        {
            get
            {
                return this.lOTTABLE36Field;
            }
            set
            {
                this.lOTTABLE36Field = value;
            }
        }

        public string LOTTABLE37
        {
            get
            {
                return this.lOTTABLE37Field;
            }
            set
            {
                this.lOTTABLE37Field = value;
            }
        }

        public string LOTTABLE38
        {
            get
            {
                return this.lOTTABLE38Field;
            }
            set
            {
                this.lOTTABLE38Field = value;
            }
        }

        public string LOTTABLE39
        {
            get
            {
                return this.lOTTABLE39Field;
            }
            set
            {
                this.lOTTABLE39Field = value;
            }
        }

        public string LOTTABLE40
        {
            get
            {
                return this.lOTTABLE40Field;
            }
            set
            {
                this.lOTTABLE40Field = value;
            }
        }

        public string LOTTABLE41
        {
            get
            {
                return this.lOTTABLE41Field;
            }
            set
            {
                this.lOTTABLE41Field = value;
            }
        }

        public string LOTTABLE42
        {
            get
            {
                return this.lOTTABLE42Field;
            }
            set
            {
                this.lOTTABLE42Field = value;
            }
        }

        public string LOTTABLE43
        {
            get
            {
                return this.lOTTABLE43Field;
            }
            set
            {
                this.lOTTABLE43Field = value;
            }
        }

        public string LOTTABLE44
        {
            get
            {
                return this.lOTTABLE44Field;
            }
            set
            {
                this.lOTTABLE44Field = value;
            }
        }

        public string LOTTABLE45
        {
            get
            {
                return this.lOTTABLE45Field;
            }
            set
            {
                this.lOTTABLE45Field = value;
            }
        }

        public string LOTTABLE46
        {
            get
            {
                return this.lOTTABLE46Field;
            }
            set
            {
                this.lOTTABLE46Field = value;
            }
        }

        public string LOTTABLE47
        {
            get
            {
                return this.lOTTABLE47Field;
            }
            set
            {
                this.lOTTABLE47Field = value;
            }
        }

        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public string errmsg
        {
            get
            {
                return this.errmsgField;
            }
            set
            {
                this.errmsgField = value;
            }
        }

        public string rectype
        {
            get
            {
                return this.rectypeField;
            }
            set
            {
                this.rectypeField = value;
            }
        }

        public string rectotal
        {
            get
            {
                return this.rectotalField;
            }
            set
            {
                this.rectotalField = value;
            }
        }

        public string dateFormate
        {
            get
            {
                return this.dateFormateField;
            }
            set
            {
                this.dateFormateField = value;
            }
        }
    }

}
