// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>InfoWms.API</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.FLGETSKUINFOP1S1.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Utility
    {
        public static Utility CreateByAsnSku(string asn, string linenum, string sku, string storerkey)
        {
            Utility data = new Utility();
            data.UtilityHeader.pro = asn;
            data.UtilityHeader.sku = sku;
            data.UtilityHeader.storerkey = storerkey;
            data.UtilityHeader.receiptLineNumber = linenum;


            return data;
        }

        private UtilityHeader utilityHeaderField;

        public Utility()
        {
            this.utilityHeaderField = new UtilityHeader();
        }

        public UtilityHeader UtilityHeader
        {
            get
            {
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }

        #region Clone method
        /// <summary>
        /// Create a clone of this Utility object
        /// </summary>
        public virtual Utility Clone()
        {
            return ((Utility)(this.MemberwiseClone()));
        }
        #endregion
    }

    public partial class UtilityHeader
    {

        private string procNameField;

        private string sendDelimiterField;

        private string ptcidField;

        private string useridField;

        private string taskIdField;

        private string databasenameField;

        private string appflagField;

        private string recordTypeField;

        private string serverField;

        private string storerkeyField;

        private string skuField;

        private string proField;

        private string receiptLineNumberField;

        public UtilityHeader()
        {
            this.procNameField = "NSPRFASNGSI01FL";
            this.sendDelimiterField = "`";
            this.taskIdField = "0";
        }

        public string ProcName
        {
            get
            {
                return this.procNameField;
            }
            set
            {
                this.procNameField = value;
            }
        }

        public string sendDelimiter
        {
            get
            {
                return this.sendDelimiterField;
            }
            set
            {
                this.sendDelimiterField = value;
            }
        }

        public string ptcid
        {
            get
            {
                return this.ptcidField;
            }
            set
            {
                this.ptcidField = value;
            }
        }

        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }

        public string taskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }

        public string databasename
        {
            get
            {
                return this.databasenameField;
            }
            set
            {
                this.databasenameField = value;
            }
        }

        public string appflag
        {
            get
            {
                return this.appflagField;
            }
            set
            {
                this.appflagField = value;
            }
        }

        public string recordType
        {
            get
            {
                return this.recordTypeField;
            }
            set
            {
                this.recordTypeField = value;
            }
        }

        public string server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }

        public string storerkey
        {
            get
            {
                return this.storerkeyField;
            }
            set
            {
                this.storerkeyField = value;
            }
        }

        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }

        public string pro
        {
            get
            {
                return this.proField;
            }
            set
            {
                this.proField = value;
            }
        }

        public string receiptLineNumber
        {
            get
            {
                return this.receiptLineNumberField;
            }
            set
            {
                this.receiptLineNumberField = value;
            }
        }

        #region Clone method
        /// <summary>
        /// Create a clone of this UtilityUtilityHeader object
        /// </summary>
        public virtual UtilityHeader Clone()
        {
            return ((UtilityHeader)(this.MemberwiseClone()));
        }
        #endregion
    }
}
