// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>InfoWms.API</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.FLGETSKUINFOP1S1.Response
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Utility
    {

        private UtilityHeader utilityHeaderField;

        public UtilityHeader UtilityHeader
        {
            get
            {
                if ((this.utilityHeaderField == null))
                {
                    this.utilityHeaderField = new UtilityHeader();
                }
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }

        #region Clone method
        /// <summary>
        /// Create a clone of this Utility object
        /// </summary>
        public virtual Utility Clone()
        {
            return ((Utility)(this.MemberwiseClone()));
        }
        #endregion
    }

    public partial class UtilityHeader
    {

        private string storerKeyField;

        private string masterskuField;

        private string descField;

        private string packField;

        private string uOMField;

        private string putawayZoneField;

        private string sUsr1Field;

        private string sUsr2Field;

        private string sUsr3Field;

        private string sUsr4Field;

        private string sUsr5Field;

        private string iAVGWGTField;

        private string l_IOTHER1Field;

        private string l_IOTHER2Field;

        private string l_IOTHER3Field;

        private string oAVGWGTField;

        private string l_OOTHER1Field;

        private string l_OOTHER2Field;

        private string l_OOTHER3Field;

        private string vISIWGTField;

        private string vISIOTH1Field;

        private string vISIOTH2Field;

        private string vISIOTH3Field;

        private string vISOWGTField;

        private string vISOOTH1Field;

        private string vISOOTH2Field;

        private string vISOOTH3Field;

        private string iALLOWTOTALField;

        private string oALLOWTOTALField;

        private string l_IOTHER4Field;

        private string l_IOTHER5Field;

        private string vISIOTH4Field;

        private string vISIOTH5Field;

        private string l_OOTHER4Field;

        private string l_OOTHER5Field;

        private string vISOOTH4Field;

        private string vISOOTH5Field;

        private string field1Field;

        private string field2Field;

        private string field3Field;

        private string field4Field;

        private string field5Field;

        private string field6Field;

        private string field7Field;

        private string field8Field;

        private string field9Field;

        private string field10Field;

        private string field11Field;

        private string field12Field;

        private string field13Field;

        private string field14Field;

        private string field15Field;

        private string field16Field;

        private string field17Field;

        private string field18Field;

        private string field19Field;

        private string field20Field;

        private string field21Field;

        private string field22Field;

        private string field23Field;

        private string field24Field;

        private string field25Field;

        private string field26Field;

        private string field27Field;

        private string field28Field;

        private string field29Field;

        private string field30Field;

        private string field31Field;

        private string field32Field;

        private string field33Field;

        private string field34Field;

        private string field35Field;

        private string field36Field;

        private string field37Field;

        private string field38Field;

        private string field39Field;

        private string field40Field;

        private string field41Field;

        private string field42Field;

        private string field43Field;

        private string field44Field;

        private string field45Field;

        private string field46Field;

        private string field47Field;

        private string field48Field;

        private string field49Field;

        private string field50Field;

        private string field51Field;

        private string field52Field;

        private string field53Field;

        private string field54Field;

        private string field55Field;

        private string field56Field;

        private string field57Field;

        private string field58Field;

        private string field59Field;

        private string field60Field;

        private string field61Field;

        private string field62Field;

        private string field63Field;

        private string field64Field;

        private string field65Field;

        private string field66Field;

        private string field67Field;

        private string field68Field;

        private string field69Field;

        private string field70Field;

        private string field71Field;

        private string field72Field;

        private string field73Field;

        private string field74Field;

        private string field75Field;

        private string field76Field;

        private string field77Field;

        private string field78Field;

        private string field79Field;

        private string field80Field;

        private string field81Field;

        private string field82Field;

        private string field83Field;

        private string field84Field;

        private string field85Field;

        private string field86Field;

        private string field87Field;

        private string field88Field;

        private string field89Field;

        private string field90Field;

        private string field91Field;

        private string field92Field;

        private string field93Field;

        private string field94Field;

        private string clwsField;

        private string visitempField;

        private string temperatureField;

        private string lo1Field;

        private string lo2Field;

        private string lo3Field;

        private string lo4Field;

        private string lo5Field;

        private string lo6Field;

        private string lo7Field;

        private string lo8Field;

        private string lo9Field;

        private string lo10Field;

        private string lo11Field;

        private string lo12Field;

        private string lo13Field;

        private string lo14Field;

        private string lo15Field;

        private string lo16Field;

        private string lo17Field;

        private string lo18Field;

        private string lo19Field;

        private string lo20Field;

        private string lo21Field;

        private string lo22Field;

        private string lo23Field;

        private string lo24Field;

        private string lo25Field;

        private string lo26Field;

        private string lo27Field;

        private string lo28Field;

        private string lo29Field;

        private string lo30Field;

        private string lo31Field;

        private string lo32Field;

        private string lo33Field;

        private string lo34Field;

        private string lo35Field;

        private string lo36Field;

        private string lo37Field;

        private string lo38Field;

        private string lo39Field;

        private string lo40Field;

        private string lo41Field;

        private string lo42Field;

        private string lo43Field;

        private string lo44Field;

        private string lo45Field;

        private string lo46Field;

        private string lo47Field;

        private string lottable1Field;

        private string lottable2Field;

        private string lottable3Field;
        private string lottable4Field;
        private string lottable5Field;

        private string lottable6Field;

        private string lottable7Field;

        private string lottable8Field;

        private string lottable9Field;

        private string lottable10Field;

        private string lottable11Field;

        private string lottable12Field;

        private string lottable13Field;

        private string lottable14Field;

        private string lottable15Field;

        private string lottable16Field;

        private string lottable17Field;

        private string lottable18Field;

        private string lottable19Field;

        private string lottable20Field;

        private string lottable21Field;

        private string lottable22Field;

        private string lottable23Field;

        private string lottable24Field;

        private string lottable25Field;

        private string lottable26Field;

        private string lottable27Field;

        private string lottable28Field;

        private string lottable29Field;

        private string lottable30Field;

        private string lottable31Field;

        private string lottable32Field;

        private string lottable33Field;

        private string lottable34Field;

        private string lottable35Field;

        private string lottable36Field;

        private string lottable37Field;

        private string lottable38Field;

        private string lottable39Field;

        private string lottable40Field;

        private string lottable41Field;

        private string lottable42Field;

        private string lottable43Field;

        private string lottable44Field;

        private string lottable45Field;

        private string ise2eField;
        private string VISISRPField;

        private string proField;

        private string holdField;

        public string StorerKey
        {
            get
            {
                return this.storerKeyField;
            }
            set
            {
                this.storerKeyField = value;
            }
        }

        public string mastersku
        {
            get
            {
                return this.masterskuField;
            }
            set
            {
                this.masterskuField = value;
            }
        }

        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        public string pack
        {
            get
            {
                return this.packField;
            }
            set
            {
                this.packField = value;
            }
        }

        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        public string PutawayZone
        {
            get
            {
                return this.putawayZoneField;
            }
            set
            {
                this.putawayZoneField = value;
            }
        }

        public string SUsr1
        {
            get
            {
                return this.sUsr1Field;
            }
            set
            {
                this.sUsr1Field = value;
            }
        }

        public string SUsr2
        {
            get
            {
                return this.sUsr2Field;
            }
            set
            {
                this.sUsr2Field = value;
            }
        }

        public string SUsr3
        {
            get
            {
                return this.sUsr3Field;
            }
            set
            {
                this.sUsr3Field = value;
            }
        }

        public string SUsr4
        {
            get
            {
                return this.sUsr4Field;
            }
            set
            {
                this.sUsr4Field = value;
            }
        }

        public string SUsr5
        {
            get
            {
                return this.sUsr5Field;
            }
            set
            {
                this.sUsr5Field = value;
            }
        }

        public string IAVGWGT
        {
            get
            {
                return this.iAVGWGTField;
            }
            set
            {
                this.iAVGWGTField = value;
            }
        }

        public string L_IOTHER1
        {
            get
            {
                return this.l_IOTHER1Field;
            }
            set
            {
                this.l_IOTHER1Field = value;
            }
        }

        public string L_IOTHER2
        {
            get
            {
                return this.l_IOTHER2Field;
            }
            set
            {
                this.l_IOTHER2Field = value;
            }
        }

        public string L_IOTHER3
        {
            get
            {
                return this.l_IOTHER3Field;
            }
            set
            {
                this.l_IOTHER3Field = value;
            }
        }

        public string OAVGWGT
        {
            get
            {
                return this.oAVGWGTField;
            }
            set
            {
                this.oAVGWGTField = value;
            }
        }

        public string L_OOTHER1
        {
            get
            {
                return this.l_OOTHER1Field;
            }
            set
            {
                this.l_OOTHER1Field = value;
            }
        }

        public string L_OOTHER2
        {
            get
            {
                return this.l_OOTHER2Field;
            }
            set
            {
                this.l_OOTHER2Field = value;
            }
        }

        public string L_OOTHER3
        {
            get
            {
                return this.l_OOTHER3Field;
            }
            set
            {
                this.l_OOTHER3Field = value;
            }
        }

        public string VISIWGT
        {
            get
            {
                return this.vISIWGTField;
            }
            set
            {
                this.vISIWGTField = value;
            }
        }

        public string VISIOTH1
        {
            get
            {
                return this.vISIOTH1Field;
            }
            set
            {
                this.vISIOTH1Field = value;
            }
        }

        public string VISIOTH2
        {
            get
            {
                return this.vISIOTH2Field;
            }
            set
            {
                this.vISIOTH2Field = value;
            }
        }

        public string VISIOTH3
        {
            get
            {
                return this.vISIOTH3Field;
            }
            set
            {
                this.vISIOTH3Field = value;
            }
        }

        public string VISOWGT
        {
            get
            {
                return this.vISOWGTField;
            }
            set
            {
                this.vISOWGTField = value;
            }
        }

        public string VISOOTH1
        {
            get
            {
                return this.vISOOTH1Field;
            }
            set
            {
                this.vISOOTH1Field = value;
            }
        }

        public string VISOOTH2
        {
            get
            {
                return this.vISOOTH2Field;
            }
            set
            {
                this.vISOOTH2Field = value;
            }
        }

        public string VISOOTH3
        {
            get
            {
                return this.vISOOTH3Field;
            }
            set
            {
                this.vISOOTH3Field = value;
            }
        }

        public string IALLOWTOTAL
        {
            get
            {
                return this.iALLOWTOTALField;
            }
            set
            {
                this.iALLOWTOTALField = value;
            }
        }

        public string OALLOWTOTAL
        {
            get
            {
                return this.oALLOWTOTALField;
            }
            set
            {
                this.oALLOWTOTALField = value;
            }
        }

        public string L_IOTHER4
        {
            get
            {
                return this.l_IOTHER4Field;
            }
            set
            {
                this.l_IOTHER4Field = value;
            }
        }

        public string L_IOTHER5
        {
            get
            {
                return this.l_IOTHER5Field;
            }
            set
            {
                this.l_IOTHER5Field = value;
            }
        }

        public string VISIOTH4
        {
            get
            {
                return this.vISIOTH4Field;
            }
            set
            {
                this.vISIOTH4Field = value;
            }
        }

        public string VISIOTH5
        {
            get
            {
                return this.vISIOTH5Field;
            }
            set
            {
                this.vISIOTH5Field = value;
            }
        }

        public string L_OOTHER4
        {
            get
            {
                return this.l_OOTHER4Field;
            }
            set
            {
                this.l_OOTHER4Field = value;
            }
        }

        public string L_OOTHER5
        {
            get
            {
                return this.l_OOTHER5Field;
            }
            set
            {
                this.l_OOTHER5Field = value;
            }
        }

        public string VISOOTH4
        {
            get
            {
                return this.vISOOTH4Field;
            }
            set
            {
                this.vISOOTH4Field = value;
            }
        }

        public string VISOOTH5
        {
            get
            {
                return this.vISOOTH5Field;
            }
            set
            {
                this.vISOOTH5Field = value;
            }
        }

        public string Field1
        {
            get
            {
                return this.field1Field;
            }
            set
            {
                this.field1Field = value;
            }
        }

        public string Field2
        {
            get
            {
                return this.field2Field;
            }
            set
            {
                this.field2Field = value;
            }
        }

        public string Field3
        {
            get
            {
                return this.field3Field;
            }
            set
            {
                this.field3Field = value;
            }
        }

        public string Field4
        {
            get
            {
                return this.field4Field;
            }
            set
            {
                this.field4Field = value;
            }
        }

        public string Field5
        {
            get
            {
                return this.field5Field;
            }
            set
            {
                this.field5Field = value;
            }
        }

        public string Field6
        {
            get
            {
                return this.field6Field;
            }
            set
            {
                this.field6Field = value;
            }
        }

        public string Field7
        {
            get
            {
                return this.field7Field;
            }
            set
            {
                this.field7Field = value;
            }
        }

        public string Field8
        {
            get
            {
                return this.field8Field;
            }
            set
            {
                this.field8Field = value;
            }
        }

        public string Field9
        {
            get
            {
                return this.field9Field;
            }
            set
            {
                this.field9Field = value;
            }
        }

        public string Field10
        {
            get
            {
                return this.field10Field;
            }
            set
            {
                this.field10Field = value;
            }
        }

        public string Field11
        {
            get
            {
                return this.field11Field;
            }
            set
            {
                this.field11Field = value;
            }
        }

        public string Field12
        {
            get
            {
                return this.field12Field;
            }
            set
            {
                this.field12Field = value;
            }
        }

        public string Field13
        {
            get
            {
                return this.field13Field;
            }
            set
            {
                this.field13Field = value;
            }
        }

        public string Field14
        {
            get
            {
                return this.field14Field;
            }
            set
            {
                this.field14Field = value;
            }
        }

        public string Field15
        {
            get
            {
                return this.field15Field;
            }
            set
            {
                this.field15Field = value;
            }
        }

        public string Field16
        {
            get
            {
                return this.field16Field;
            }
            set
            {
                this.field16Field = value;
            }
        }

        public string Field17
        {
            get
            {
                return this.field17Field;
            }
            set
            {
                this.field17Field = value;
            }
        }

        public string Field18
        {
            get
            {
                return this.field18Field;
            }
            set
            {
                this.field18Field = value;
            }
        }

        public string Field19
        {
            get
            {
                return this.field19Field;
            }
            set
            {
                this.field19Field = value;
            }
        }

        public string Field20
        {
            get
            {
                return this.field20Field;
            }
            set
            {
                this.field20Field = value;
            }
        }

        public string Field21
        {
            get
            {
                return this.field21Field;
            }
            set
            {
                this.field21Field = value;
            }
        }

        public string Field22
        {
            get
            {
                return this.field22Field;
            }
            set
            {
                this.field22Field = value;
            }
        }

        public string Field23
        {
            get
            {
                return this.field23Field;
            }
            set
            {
                this.field23Field = value;
            }
        }

        public string Field24
        {
            get
            {
                return this.field24Field;
            }
            set
            {
                this.field24Field = value;
            }
        }

        public string Field25
        {
            get
            {
                return this.field25Field;
            }
            set
            {
                this.field25Field = value;
            }
        }

        public string Field26
        {
            get
            {
                return this.field26Field;
            }
            set
            {
                this.field26Field = value;
            }
        }

        public string Field27
        {
            get
            {
                return this.field27Field;
            }
            set
            {
                this.field27Field = value;
            }
        }

        public string Field28
        {
            get
            {
                return this.field28Field;
            }
            set
            {
                this.field28Field = value;
            }
        }

        public string Field29
        {
            get
            {
                return this.field29Field;
            }
            set
            {
                this.field29Field = value;
            }
        }

        public string Field30
        {
            get
            {
                return this.field30Field;
            }
            set
            {
                this.field30Field = value;
            }
        }

        public string Field31
        {
            get
            {
                return this.field31Field;
            }
            set
            {
                this.field31Field = value;
            }
        }

        public string Field32
        {
            get
            {
                return this.field32Field;
            }
            set
            {
                this.field32Field = value;
            }
        }

        public string Field33
        {
            get
            {
                return this.field33Field;
            }
            set
            {
                this.field33Field = value;
            }
        }

        public string Field34
        {
            get
            {
                return this.field34Field;
            }
            set
            {
                this.field34Field = value;
            }
        }

        public string Field35
        {
            get
            {
                return this.field35Field;
            }
            set
            {
                this.field35Field = value;
            }
        }

        public string Field36
        {
            get
            {
                return this.field36Field;
            }
            set
            {
                this.field36Field = value;
            }
        }

        public string Field37
        {
            get
            {
                return this.field37Field;
            }
            set
            {
                this.field37Field = value;
            }
        }

        public string Field38
        {
            get
            {
                return this.field38Field;
            }
            set
            {
                this.field38Field = value;
            }
        }

        public string Field39
        {
            get
            {
                return this.field39Field;
            }
            set
            {
                this.field39Field = value;
            }
        }

        public string Field40
        {
            get
            {
                return this.field40Field;
            }
            set
            {
                this.field40Field = value;
            }
        }

        public string Field41
        {
            get
            {
                return this.field41Field;
            }
            set
            {
                this.field41Field = value;
            }
        }

        public string Field42
        {
            get
            {
                return this.field42Field;
            }
            set
            {
                this.field42Field = value;
            }
        }

        public string Field43
        {
            get
            {
                return this.field43Field;
            }
            set
            {
                this.field43Field = value;
            }
        }

        public string Field44
        {
            get
            {
                return this.field44Field;
            }
            set
            {
                this.field44Field = value;
            }
        }

        public string Field45
        {
            get
            {
                return this.field45Field;
            }
            set
            {
                this.field45Field = value;
            }
        }

        public string Field46
        {
            get
            {
                return this.field46Field;
            }
            set
            {
                this.field46Field = value;
            }
        }

        public string Field47
        {
            get
            {
                return this.field47Field;
            }
            set
            {
                this.field47Field = value;
            }
        }

        public string Field48
        {
            get
            {
                return this.field48Field;
            }
            set
            {
                this.field48Field = value;
            }
        }

        public string Field49
        {
            get
            {
                return this.field49Field;
            }
            set
            {
                this.field49Field = value;
            }
        }

        public string Field50
        {
            get
            {
                return this.field50Field;
            }
            set
            {
                this.field50Field = value;
            }
        }

        public string Field51
        {
            get
            {
                return this.field51Field;
            }
            set
            {
                this.field51Field = value;
            }
        }

        public string Field52
        {
            get
            {
                return this.field52Field;
            }
            set
            {
                this.field52Field = value;
            }
        }

        public string Field53
        {
            get
            {
                return this.field53Field;
            }
            set
            {
                this.field53Field = value;
            }
        }

        public string Field54
        {
            get
            {
                return this.field54Field;
            }
            set
            {
                this.field54Field = value;
            }
        }

        public string Field55
        {
            get
            {
                return this.field55Field;
            }
            set
            {
                this.field55Field = value;
            }
        }

        public string Field56
        {
            get
            {
                return this.field56Field;
            }
            set
            {
                this.field56Field = value;
            }
        }

        public string Field57
        {
            get
            {
                return this.field57Field;
            }
            set
            {
                this.field57Field = value;
            }
        }

        public string Field58
        {
            get
            {
                return this.field58Field;
            }
            set
            {
                this.field58Field = value;
            }
        }

        public string Field59
        {
            get
            {
                return this.field59Field;
            }
            set
            {
                this.field59Field = value;
            }
        }

        public string Field60
        {
            get
            {
                return this.field60Field;
            }
            set
            {
                this.field60Field = value;
            }
        }

        public string Field61
        {
            get
            {
                return this.field61Field;
            }
            set
            {
                this.field61Field = value;
            }
        }

        public string Field62
        {
            get
            {
                return this.field62Field;
            }
            set
            {
                this.field62Field = value;
            }
        }

        public string Field63
        {
            get
            {
                return this.field63Field;
            }
            set
            {
                this.field63Field = value;
            }
        }

        public string Field64
        {
            get
            {
                return this.field64Field;
            }
            set
            {
                this.field64Field = value;
            }
        }

        public string Field65
        {
            get
            {
                return this.field65Field;
            }
            set
            {
                this.field65Field = value;
            }
        }

        public string Field66
        {
            get
            {
                return this.field66Field;
            }
            set
            {
                this.field66Field = value;
            }
        }

        public string Field67
        {
            get
            {
                return this.field67Field;
            }
            set
            {
                this.field67Field = value;
            }
        }

        public string Field68
        {
            get
            {
                return this.field68Field;
            }
            set
            {
                this.field68Field = value;
            }
        }

        public string Field69
        {
            get
            {
                return this.field69Field;
            }
            set
            {
                this.field69Field = value;
            }
        }

        public string Field70
        {
            get
            {
                return this.field70Field;
            }
            set
            {
                this.field70Field = value;
            }
        }

        public string Field71
        {
            get
            {
                return this.field71Field;
            }
            set
            {
                this.field71Field = value;
            }
        }

        public string Field72
        {
            get
            {
                return this.field72Field;
            }
            set
            {
                this.field72Field = value;
            }
        }

        public string Field73
        {
            get
            {
                return this.field73Field;
            }
            set
            {
                this.field73Field = value;
            }
        }

        public string Field74
        {
            get
            {
                return this.field74Field;
            }
            set
            {
                this.field74Field = value;
            }
        }

        public string Field75
        {
            get
            {
                return this.field75Field;
            }
            set
            {
                this.field75Field = value;
            }
        }

        public string Field76
        {
            get
            {
                return this.field76Field;
            }
            set
            {
                this.field76Field = value;
            }
        }

        public string Field77
        {
            get
            {
                return this.field77Field;
            }
            set
            {
                this.field77Field = value;
            }
        }

        public string Field78
        {
            get
            {
                return this.field78Field;
            }
            set
            {
                this.field78Field = value;
            }
        }

        public string Field79
        {
            get
            {
                return this.field79Field;
            }
            set
            {
                this.field79Field = value;
            }
        }

        public string Field80
        {
            get
            {
                return this.field80Field;
            }
            set
            {
                this.field80Field = value;
            }
        }

        public string Field81
        {
            get
            {
                return this.field81Field;
            }
            set
            {
                this.field81Field = value;
            }
        }

        public string Field82
        {
            get
            {
                return this.field82Field;
            }
            set
            {
                this.field82Field = value;
            }
        }

        public string Field83
        {
            get
            {
                return this.field83Field;
            }
            set
            {
                this.field83Field = value;
            }
        }

        public string Field84
        {
            get
            {
                return this.field84Field;
            }
            set
            {
                this.field84Field = value;
            }
        }

        public string Field85
        {
            get
            {
                return this.field85Field;
            }
            set
            {
                this.field85Field = value;
            }
        }

        public string Field86
        {
            get
            {
                return this.field86Field;
            }
            set
            {
                this.field86Field = value;
            }
        }

        public string Field87
        {
            get
            {
                return this.field87Field;
            }
            set
            {
                this.field87Field = value;
            }
        }

        public string Field88
        {
            get
            {
                return this.field88Field;
            }
            set
            {
                this.field88Field = value;
            }
        }

        public string Field89
        {
            get
            {
                return this.field89Field;
            }
            set
            {
                this.field89Field = value;
            }
        }

        public string Field90
        {
            get
            {
                return this.field90Field;
            }
            set
            {
                this.field90Field = value;
            }
        }

        public string Field91
        {
            get
            {
                return this.field91Field;
            }
            set
            {
                this.field91Field = value;
            }
        }

        public string Field92
        {
            get
            {
                return this.field92Field;
            }
            set
            {
                this.field92Field = value;
            }
        }

        public string Field93
        {
            get
            {
                return this.field93Field;
            }
            set
            {
                this.field93Field = value;
            }
        }

        public string Field94
        {
            get
            {
                return this.field94Field;
            }
            set
            {
                this.field94Field = value;
            }
        }

        public string clws
        {
            get
            {
                return this.clwsField;
            }
            set
            {
                this.clwsField = value;
            }
        }

        public string visitemp
        {
            get
            {
                return this.visitempField;
            }
            set
            {
                this.visitempField = value;
            }
        }

        public string Temperature
        {
            get
            {
                return this.temperatureField;
            }
            set
            {
                this.temperatureField = value;
            }
        }

        public string lo1
        {
            get
            {
                return this.lo1Field;
            }
            set
            {
                this.lo1Field = value;
            }
        }

        public string lo2
        {
            get
            {
                return this.lo2Field;
            }
            set
            {
                this.lo2Field = value;
            }
        }

        public string lo3
        {
            get
            {
                return this.lo3Field;
            }
            set
            {
                this.lo3Field = value;
            }
        }

        public string lo4
        {
            get
            {
                return this.lo4Field;
            }
            set
            {
                this.lo4Field = value;
            }
        }

        public string lo5
        {
            get
            {
                return this.lo5Field;
            }
            set
            {
                this.lo5Field = value;
            }
        }

        public string lo6
        {
            get
            {
                return this.lo6Field;
            }
            set
            {
                this.lo6Field = value;
            }
        }

        public string lo7
        {
            get
            {
                return this.lo7Field;
            }
            set
            {
                this.lo7Field = value;
            }
        }

        public string lo8
        {
            get
            {
                return this.lo8Field;
            }
            set
            {
                this.lo8Field = value;
            }
        }

        public string lo9
        {
            get
            {
                return this.lo9Field;
            }
            set
            {
                this.lo9Field = value;
            }
        }

        public string lo10
        {
            get
            {
                return this.lo10Field;
            }
            set
            {
                this.lo10Field = value;
            }
        }

        public string lo11
        {
            get
            {
                return this.lo11Field;
            }
            set
            {
                this.lo11Field = value;
            }
        }

        public string lo12
        {
            get
            {
                return this.lo12Field;
            }
            set
            {
                this.lo12Field = value;
            }
        }

        public string lo13
        {
            get
            {
                return this.lo13Field;
            }
            set
            {
                this.lo13Field = value;
            }
        }

        public string lo14
        {
            get
            {
                return this.lo14Field;
            }
            set
            {
                this.lo14Field = value;
            }
        }

        public string lo15
        {
            get
            {
                return this.lo15Field;
            }
            set
            {
                this.lo15Field = value;
            }
        }

        public string lo16
        {
            get
            {
                return this.lo16Field;
            }
            set
            {
                this.lo16Field = value;
            }
        }

        public string lo17
        {
            get
            {
                return this.lo17Field;
            }
            set
            {
                this.lo17Field = value;
            }
        }

        public string lo18
        {
            get
            {
                return this.lo18Field;
            }
            set
            {
                this.lo18Field = value;
            }
        }

        public string lo19
        {
            get
            {
                return this.lo19Field;
            }
            set
            {
                this.lo19Field = value;
            }
        }

        public string lo20
        {
            get
            {
                return this.lo20Field;
            }
            set
            {
                this.lo20Field = value;
            }
        }

        public string lo21
        {
            get
            {
                return this.lo21Field;
            }
            set
            {
                this.lo21Field = value;
            }
        }

        public string lo22
        {
            get
            {
                return this.lo22Field;
            }
            set
            {
                this.lo22Field = value;
            }
        }

        public string lo23
        {
            get
            {
                return this.lo23Field;
            }
            set
            {
                this.lo23Field = value;
            }
        }

        public string lo24
        {
            get
            {
                return this.lo24Field;
            }
            set
            {
                this.lo24Field = value;
            }
        }

        public string lo25
        {
            get
            {
                return this.lo25Field;
            }
            set
            {
                this.lo25Field = value;
            }
        }

        public string lo26
        {
            get
            {
                return this.lo26Field;
            }
            set
            {
                this.lo26Field = value;
            }
        }

        public string lo27
        {
            get
            {
                return this.lo27Field;
            }
            set
            {
                this.lo27Field = value;
            }
        }

        public string lo28
        {
            get
            {
                return this.lo28Field;
            }
            set
            {
                this.lo28Field = value;
            }
        }

        public string lo29
        {
            get
            {
                return this.lo29Field;
            }
            set
            {
                this.lo29Field = value;
            }
        }

        public string lo30
        {
            get
            {
                return this.lo30Field;
            }
            set
            {
                this.lo30Field = value;
            }
        }

        public string lo31
        {
            get
            {
                return this.lo31Field;
            }
            set
            {
                this.lo31Field = value;
            }
        }

        public string lo32
        {
            get
            {
                return this.lo32Field;
            }
            set
            {
                this.lo32Field = value;
            }
        }

        public string lo33
        {
            get
            {
                return this.lo33Field;
            }
            set
            {
                this.lo33Field = value;
            }
        }

        public string lo34
        {
            get
            {
                return this.lo34Field;
            }
            set
            {
                this.lo34Field = value;
            }
        }

        public string lo35
        {
            get
            {
                return this.lo35Field;
            }
            set
            {
                this.lo35Field = value;
            }
        }

        public string lo36
        {
            get
            {
                return this.lo36Field;
            }
            set
            {
                this.lo36Field = value;
            }
        }

        public string lo37
        {
            get
            {
                return this.lo37Field;
            }
            set
            {
                this.lo37Field = value;
            }
        }

        public string lo38
        {
            get
            {
                return this.lo38Field;
            }
            set
            {
                this.lo38Field = value;
            }
        }

        public string lo39
        {
            get
            {
                return this.lo39Field;
            }
            set
            {
                this.lo39Field = value;
            }
        }

        public string lo40
        {
            get
            {
                return this.lo40Field;
            }
            set
            {
                this.lo40Field = value;
            }
        }

        public string lo41
        {
            get
            {
                return this.lo41Field;
            }
            set
            {
                this.lo41Field = value;
            }
        }

        public string lo42
        {
            get
            {
                return this.lo42Field;
            }
            set
            {
                this.lo42Field = value;
            }
        }

        public string lo43
        {
            get
            {
                return this.lo43Field;
            }
            set
            {
                this.lo43Field = value;
            }
        }

        public string lo44
        {
            get
            {
                return this.lo44Field;
            }
            set
            {
                this.lo44Field = value;
            }
        }

        public string lo45
        {
            get
            {
                return this.lo45Field;
            }
            set
            {
                this.lo45Field = value;
            }
        }

        public string lo46
        {
            get
            {
                return this.lo46Field;
            }
            set
            {
                this.lo46Field = value;
            }
        }

        public string lo47
        {
            get
            {
                return this.lo47Field;
            }
            set
            {
                this.lo47Field = value;
            }
        }

        public string lottable1
        {
            get
            {
                return this.lottable1Field;
            }
            set
            {
                this.lottable1Field = value;
            }
        }

        public string lottable2
        {
            get
            {
                return this.lottable2Field;
            }
            set
            {
                this.lottable2Field = value;
            }
        }

        public string lottable3
        {
            get
            {
                return this.lottable3Field;
            }
            set
            {
                this.lottable3Field = value;
            }
        }

        public string lottable4
        {
            get
            {
                return this.lottable4Field;
            }
            set
            {
                this.lottable4Field = value;
            }
        }

        public string lottable5
        {
            get
            {
                return this.lottable5Field;
            }
            set
            {
                this.lottable5Field = value;
            }
        }

        public string lottable6
        {
            get
            {
                return this.lottable6Field;
            }
            set
            {
                this.lottable6Field = value;
            }
        }

        public string lottable7
        {
            get
            {
                return this.lottable7Field;
            }
            set
            {
                this.lottable7Field = value;
            }
        }

        public string lottable8
        {
            get
            {
                return this.lottable8Field;
            }
            set
            {
                this.lottable8Field = value;
            }
        }

        public string lottable9
        {
            get
            {
                return this.lottable9Field;
            }
            set
            {
                this.lottable9Field = value;
            }
        }

        public string Lottable10
        {
            get
            {
                return this.lottable10Field;
            }
            set
            {
                this.lottable10Field = value;
            }
        }

        public string lottable11
        {
            get
            {
                return this.lottable11Field;
            }
            set
            {
                this.lottable11Field = value;
            }
        }

        public string lottable12
        {
            get
            {
                return this.lottable12Field;
            }
            set
            {
                this.lottable12Field = value;
            }
        }

        public string lottable13
        {
            get
            {
                return this.lottable13Field;
            }
            set
            {
                this.lottable13Field = value;
            }
        }

        public string lottable14
        {
            get
            {
                return this.lottable14Field;
            }
            set
            {
                this.lottable14Field = value;
            }
        }

        public string lottable15
        {
            get
            {
                return this.lottable15Field;
            }
            set
            {
                this.lottable15Field = value;
            }
        }

        public string lottable16
        {
            get
            {
                return this.lottable16Field;
            }
            set
            {
                this.lottable16Field = value;
            }
        }

        public string lottable17
        {
            get
            {
                return this.lottable17Field;
            }
            set
            {
                this.lottable17Field = value;
            }
        }

        public string lottable18
        {
            get
            {
                return this.lottable18Field;
            }
            set
            {
                this.lottable18Field = value;
            }
        }

        public string lottable19
        {
            get
            {
                return this.lottable19Field;
            }
            set
            {
                this.lottable19Field = value;
            }
        }

        public string lottable20
        {
            get
            {
                return this.lottable20Field;
            }
            set
            {
                this.lottable20Field = value;
            }
        }

        public string lottable21
        {
            get
            {
                return this.lottable21Field;
            }
            set
            {
                this.lottable21Field = value;
            }
        }

        public string lottable22
        {
            get
            {
                return this.lottable22Field;
            }
            set
            {
                this.lottable22Field = value;
            }
        }

        public string lottable23
        {
            get
            {
                return this.lottable23Field;
            }
            set
            {
                this.lottable23Field = value;
            }
        }

        public string lottable24
        {
            get
            {
                return this.lottable24Field;
            }
            set
            {
                this.lottable24Field = value;
            }
        }

        public string lottable25
        {
            get
            {
                return this.lottable25Field;
            }
            set
            {
                this.lottable25Field = value;
            }
        }

        public string lottable26
        {
            get
            {
                return this.lottable26Field;
            }
            set
            {
                this.lottable26Field = value;
            }
        }

        public string lottable27
        {
            get
            {
                return this.lottable27Field;
            }
            set
            {
                this.lottable27Field = value;
            }
        }

        public string lottable28
        {
            get
            {
                return this.lottable28Field;
            }
            set
            {
                this.lottable28Field = value;
            }
        }

        public string lottable29
        {
            get
            {
                return this.lottable29Field;
            }
            set
            {
                this.lottable29Field = value;
            }
        }

        public string lottable30
        {
            get
            {
                return this.lottable30Field;
            }
            set
            {
                this.lottable30Field = value;
            }
        }

        public string lottable31
        {
            get
            {
                return this.lottable31Field;
            }
            set
            {
                this.lottable31Field = value;
            }
        }

        public string lottable32
        {
            get
            {
                return this.lottable32Field;
            }
            set
            {
                this.lottable32Field = value;
            }
        }

        public string lottable33
        {
            get
            {
                return this.lottable33Field;
            }
            set
            {
                this.lottable33Field = value;
            }
        }

        public string lottable34
        {
            get
            {
                return this.lottable34Field;
            }
            set
            {
                this.lottable34Field = value;
            }
        }

        public string lottable35
        {
            get
            {
                return this.lottable35Field;
            }
            set
            {
                this.lottable35Field = value;
            }
        }

        public string lottable36
        {
            get
            {
                return this.lottable36Field;
            }
            set
            {
                this.lottable36Field = value;
            }
        }

        public string lottable37
        {
            get
            {
                return this.lottable37Field;
            }
            set
            {
                this.lottable37Field = value;
            }
        }

        public string lottable38
        {
            get
            {
                return this.lottable38Field;
            }
            set
            {
                this.lottable38Field = value;
            }
        }

        public string lottable39
        {
            get
            {
                return this.lottable39Field;
            }
            set
            {
                this.lottable39Field = value;
            }
        }

        public string lottable40
        {
            get
            {
                return this.lottable40Field;
            }
            set
            {
                this.lottable40Field = value;
            }
        }

        public string lottable41
        {
            get
            {
                return this.lottable41Field;
            }
            set
            {
                this.lottable41Field = value;
            }
        }

        public string lottable42
        {
            get
            {
                return this.lottable42Field;
            }
            set
            {
                this.lottable42Field = value;
            }
        }

        public string lottable43
        {
            get
            {
                return this.lottable43Field;
            }
            set
            {
                this.lottable43Field = value;
            }
        }

        public string lottable44
        {
            get
            {
                return this.lottable44Field;
            }
            set
            {
                this.lottable44Field = value;
            }
        }

        public string lottable45
        {
            get
            {
                return this.lottable45Field;
            }
            set
            {
                this.lottable45Field = value;
            }
        }

        public string ise2e
        {
            get
            {
                return this.ise2eField;
            }
            set
            {
                this.ise2eField = value;
            }
        }

        public string VISISRP
        {
            get
            {
                return this.VISISRPField;
            }
            set
            {
                this.VISISRPField = value;
            }
        }

        public string pro
        {
            get
            {
                return this.proField;
            }
            set
            {
                this.proField = value;
            }
        }

        public string hold
        {
            get
            {
                return this.holdField;
            }
            set
            {
                this.holdField = value;
            }
        }

        #region Clone method
        /// <summary>
        /// Create a clone of this UtilityUtilityHeader object
        /// </summary>
        public virtual UtilityHeader Clone()
        {
            return ((UtilityHeader)(this.MemberwiseClone()));
        }
        #endregion

        public  object GetPropValue(string propName)
        {
            return this.GetType().GetProperty(propName).GetValue(this, new object[] { });
        }

         
    }
}
