// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>InfoWms.API</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.FLRFRECEIVEByLine.Response
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Utility
    {

        private UtilityHeader utilityHeaderField;

        public UtilityHeader UtilityHeader
        {
            get
            {
                if ((this.utilityHeaderField == null))
                {
                    this.utilityHeaderField = new UtilityHeader();
                }
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }

        #region Clone method
        /// <summary>
        /// Create a clone of this Utility object
        /// </summary>
        public virtual Utility Clone()
        {
            return ((Utility)(this.MemberwiseClone()));
        }
        #endregion
    }

    public partial class UtilityHeader
    {

        private string prokeyField;

        private string receiptLineNumberField;

        private string idField;

        private string qtyField;

        private string counterField;

        private string totallinenumberField;

        private string snumsperscanField;

        private string operTypeField;

        private string wgtField;

        private string isReturnField;

        private string retqtyField;

        private string sn_counterField;

        private string processtypeField;

        private string tranTypeField;

        private string itrnKeyField;

        private string lotField;

        private string actionField;

        private string taskkeyField;

        private string taskTypeField;

        private string laborflagField;

        private string oXDLOCField;

        private string qtyleftField;

        private string oXDtaskdetailkeyField;

        private string locField;

        private string errmsgField;
        private string rectypeField;
        private string rectotalField;
        private string dateFormateField;

        public string prokey
        {
            get
            {
                return this.prokeyField;
            }
            set
            {
                this.prokeyField = value;
            }
        }

        public string ReceiptLineNumber
        {
            get
            {
                return this.receiptLineNumberField;
            }
            set
            {
                this.receiptLineNumberField = value;
            }
        }

        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        public string counter
        {
            get
            {
                return this.counterField;
            }
            set
            {
                this.counterField = value;
            }
        }

        public string totallinenumber
        {
            get
            {
                return this.totallinenumberField;
            }
            set
            {
                this.totallinenumberField = value;
            }
        }

        public string snumsperscan
        {
            get
            {
                return this.snumsperscanField;
            }
            set
            {
                this.snumsperscanField = value;
            }
        }

        public string OperType
        {
            get
            {
                return this.operTypeField;
            }
            set
            {
                this.operTypeField = value;
            }
        }

        public string Wgt
        {
            get
            {
                return this.wgtField;
            }
            set
            {
                this.wgtField = value;
            }
        }

        public string IsReturn
        {
            get
            {
                return this.isReturnField;
            }
            set
            {
                this.isReturnField = value;
            }
        }

        public string retqty
        {
            get
            {
                return this.retqtyField;
            }
            set
            {
                this.retqtyField = value;
            }
        }

        public string sn_counter
        {
            get
            {
                return this.sn_counterField;
            }
            set
            {
                this.sn_counterField = value;
            }
        }

        public string processtype
        {
            get
            {
                return this.processtypeField;
            }
            set
            {
                this.processtypeField = value;
            }
        }

        public string TranType
        {
            get
            {
                return this.tranTypeField;
            }
            set
            {
                this.tranTypeField = value;
            }
        }

        public string ItrnKey
        {
            get
            {
                return this.itrnKeyField;
            }
            set
            {
                this.itrnKeyField = value;
            }
        }

        public string Lot
        {
            get
            {
                return this.lotField;
            }
            set
            {
                this.lotField = value;
            }
        }

        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        public string taskkey
        {
            get
            {
                return this.taskkeyField;
            }
            set
            {
                this.taskkeyField = value;
            }
        }

        public string TaskType
        {
            get
            {
                return this.taskTypeField;
            }
            set
            {
                this.taskTypeField = value;
            }
        }

        public string laborflag
        {
            get
            {
                return this.laborflagField;
            }
            set
            {
                this.laborflagField = value;
            }
        }

        public string OXDLOC
        {
            get
            {
                return this.oXDLOCField;
            }
            set
            {
                this.oXDLOCField = value;
            }
        }

        public string qtyleft
        {
            get
            {
                return this.qtyleftField;
            }
            set
            {
                this.qtyleftField = value;
            }
        }

        public string OXDtaskdetailkey
        {
            get
            {
                return this.oXDtaskdetailkeyField;
            }
            set
            {
                this.oXDtaskdetailkeyField = value;
            }
        }

        public string Loc
        {
            get
            {
                return this.locField;
            }
            set
            {
                this.locField = value;
            }
        }

        public string errmsg
        {
            get
            {
                return this.errmsgField;
            }
            set
            {
                this.errmsgField = value;
            }
        }

        public string rectype
        {
            get
            {
                return this.rectypeField;
            }
            set
            {
                this.rectypeField = value;
            }
        }

        public string rectotal
        {
            get
            {
                return this.rectotalField;
            }
            set
            {
                this.rectotalField = value;
            }
        }

        public string dateFormate
        {
            get
            {
                return this.dateFormateField;
            }
            set
            {
                this.dateFormateField = value;
            }
        }
        #region Clone method
        /// <summary>
        /// Create a clone of this UtilityUtilityHeader object
        /// </summary>
        public virtual UtilityHeader Clone()
        {
            return ((UtilityHeader)(this.MemberwiseClone()));
        }
        #endregion
    }
}
