// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.NSPRFFLREMQTY.Response</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.NSPRFFLREMQTY.Response
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Utility
    {

        private UtilityHeader utilityHeaderField;

        public UtilityHeader UtilityHeader
        {
            get
            {
                if ((this.utilityHeaderField == null))
                {
                    this.utilityHeaderField = new UtilityHeader();
                }
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }
    }

    public partial class UtilityHeader
    {

        private string remqtyField;

        private string hadpickqtyField;

        private string toLocField;

        private string fromLocField;

        private string pickDetailKeyField;

        private string shiplabelField;

        private string storerKeyField;

        private string lotField;

        private string idqtyField;

        private string nothadpickedField;

        private string locqtyField;

        private string idremqtyField;

        private string errmsgField;

        private string rectypeField;

        private string rectotalField;

        private string dateFormateField;

        public string remqty
        {
            get
            {
                return this.remqtyField;
            }
            set
            {
                this.remqtyField = value;
            }
        }

        public string hadpickqty
        {
            get
            {
                return this.hadpickqtyField;
            }
            set
            {
                this.hadpickqtyField = value;
            }
        }

        public string ToLoc
        {
            get
            {
                return this.toLocField;
            }
            set
            {
                this.toLocField = value;
            }
        }

        public string FromLoc
        {
            get
            {
                return this.fromLocField;
            }
            set
            {
                this.fromLocField = value;
            }
        }

        public string PickDetailKey
        {
            get
            {
                return this.pickDetailKeyField;
            }
            set
            {
                this.pickDetailKeyField = value;
            }
        }

        public string shiplabel
        {
            get
            {
                return this.shiplabelField;
            }
            set
            {
                this.shiplabelField = value;
            }
        }

        public string StorerKey
        {
            get
            {
                return this.storerKeyField;
            }
            set
            {
                this.storerKeyField = value;
            }
        }

        public string Lot
        {
            get
            {
                return this.lotField;
            }
            set
            {
                this.lotField = value;
            }
        }

        public string idqty
        {
            get
            {
                return this.idqtyField;
            }
            set
            {
                this.idqtyField = value;
            }
        }

        public string nothadpicked
        {
            get
            {
                return this.nothadpickedField;
            }
            set
            {
                this.nothadpickedField = value;
            }
        }

        public string locqty
        {
            get
            {
                return this.locqtyField;
            }
            set
            {
                this.locqtyField = value;
            }
        }

        public string idremqty
        {
            get
            {
                return this.idremqtyField;
            }
            set
            {
                this.idremqtyField = value;
            }
        }

        public string errmsg
        {
            get
            {
                return this.errmsgField;
            }
            set
            {
                this.errmsgField = value;
            }
        }

        public string rectype
        {
            get
            {
                return this.rectypeField;
            }
            set
            {
                this.rectypeField = value;
            }
        }

        public string rectotal
        {
            get
            {
                return this.rectotalField;
            }
            set
            {
                this.rectotalField = value;
            }
        }

        public string dateFormate
        {
            get
            {
                return this.dateFormateField;
            }
            set
            {
                this.dateFormateField = value;
            }
        }
    }
}
