//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5420 版自动生成。
// 
namespace KanbanRF.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebService() {
            //this.Url = "http://172.20.70.202/webservice.asmx";
            this.Url = "http://172.20.70.202:881/webservice.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Inbound", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Inbound(string kanbanno, string user) {
            object[] results = this.Invoke("Inbound", new object[] {
                        kanbanno,
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInbound(string kanbanno, string user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Inbound", new object[] {
                        kanbanno,
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInbound(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Outbound", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Outbound(string kanbanno, string user) {
            object[] results = this.Invoke("Outbound", new object[] {
                        kanbanno,
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOutbound(string kanbanno, string user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Outbound", new object[] {
                        kanbanno,
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOutbound(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Kanban[] Query(string sku, int status) {
            object[] results = this.Invoke("Query", new object[] {
                        sku,
                        status});
            return ((Kanban[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginQuery(string sku, int status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Query", new object[] {
                        sku,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public Kanban[] EndQuery(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Kanban[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BeignCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BeignCheck() {
            object[] results = this.Invoke("BeignCheck", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBeignCheck(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BeignCheck", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndBeignCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckIn(string kanbanno, string user) {
            object[] results = this.Invoke("CheckIn", new object[] {
                        kanbanno,
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckIn(string kanbanno, string user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckIn", new object[] {
                        kanbanno,
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCheckIn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Kanban Get(string kanbanno) {
            object[] results = this.Invoke("Get", new object[] {
                        kanbanno});
            return ((Kanban)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet(string kanbanno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get", new object[] {
                        kanbanno}, callback, asyncState);
        }
        
        /// <remarks/>
        public Kanban EndGet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Kanban)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Update(Kanban kanban) {
            object[] results = this.Invoke("Update", new object[] {
                        kanban});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(Kanban kanban, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        kanban}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateOrder(string user) {
            object[] results = this.Invoke("CreateOrder", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateOrder(string user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateOrder", new object[] {
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCreateOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Order[] GetOrder(int status, string user) {
            object[] results = this.Invoke("GetOrder", new object[] {
                        status,
                        user});
            return ((Order[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrder(int status, string user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrder", new object[] {
                        status,
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public Order[] EndGetOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Order[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndLoad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EndLoad(string orderno) {
            object[] results = this.Invoke("EndLoad", new object[] {
                        orderno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEndLoad(string orderno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EndLoad", new object[] {
                        orderno}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndEndLoad(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadKanban", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadKanban(string orderno, string platnumber, string[] kanbanno, string user) {
            object[] results = this.Invoke("LoadKanban", new object[] {
                        orderno,
                        platnumber,
                        kanbanno,
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadKanban(string orderno, string platnumber, string[] kanbanno, string user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadKanban", new object[] {
                        orderno,
                        platnumber,
                        kanbanno,
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLoadKanban(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Kanban {
        
        private int idField;
        
        private string kanbanNoField;
        
        private string storereKeyField;
        
        private string sKUField;
        
        private decimal qtyField;
        
        private int statusField;
        
        private System.DateTime checkDateField;
        
        private string checkUserField;
        
        private System.Nullable<bool> isHandField;
        
        private System.Nullable<int> changedField;
        
        private string originalKanbanNoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string KanbanNo {
            get {
                return this.kanbanNoField;
            }
            set {
                this.kanbanNoField = value;
            }
        }
        
        /// <remarks/>
        public string StorereKey {
            get {
                return this.storereKeyField;
            }
            set {
                this.storereKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CheckDate {
            get {
                return this.checkDateField;
            }
            set {
                this.checkDateField = value;
            }
        }
        
        /// <remarks/>
        public string CheckUser {
            get {
                return this.checkUserField;
            }
            set {
                this.checkUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsHand {
            get {
                return this.isHandField;
            }
            set {
                this.isHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalKanbanNo {
            get {
                return this.originalKanbanNoField;
            }
            set {
                this.originalKanbanNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Order {
        
        private int idField;
        
        private string orderNoField;
        
        private string carrierField;
        
        private string plateNumberField;
        
        private System.DateTime orderDateField;
        
        private int statusField;
        
        private System.Nullable<System.DateTime> loadedDateField;
        
        private string addUserField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        public string PlateNumber {
            get {
                return this.plateNumberField;
            }
            set {
                this.plateNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LoadedDate {
            get {
                return this.loadedDateField;
            }
            set {
                this.loadedDateField = value;
            }
        }
        
        /// <remarks/>
        public string AddUser {
            get {
                return this.addUserField;
            }
            set {
                this.addUserField = value;
            }
        }
    }
}
