// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace> RFDeviceAPP.Common.NSPRFTM01.Request</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.NSPRFINSTRUCTION02X.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;



    public partial class Utility
    {
        private UtilityHeader utilityHeaderField;

        public UtilityHeader UtilityHeader
        {
            get
            {
                if ((this.utilityHeaderField == null))
                {
                    this.utilityHeaderField = new UtilityHeader();
                }
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }
    }

    public partial class UtilityHeader
    {
        private string procNameField;
        private string sendDelimiterField;

        private string ptcidField;

        private string useridField;

        private string taskIdField;

        private string databasenameField;

        private string appflagField;

        private string recordTypeField;

        private string serverField;

        private string sourcetypeField;

        private string sourcekeyField;

        private string isendField;

        private string lable1Field;

        private string lable2Field;

        private string lable3Field;

        private string lable4Field;

        private string lable5Field;

        private string sourceLineNo1Field;

        private string sourceLineNo2Field;

        private string sourceLineNo3Field;

        private string sourceLineNo4Field;

        private string sourceLineNo5Field;

        public UtilityHeader()
        {
            this.procNameField = "NSPRFINSTRUCTION02X";
            this.sendDelimiterField = "`";
            this.ptcidField = "";
            this.useridField = "sceadmin";
            this.taskIdField = "";
            this.databasenameField = "";
            this.appflagField = "";
            this.recordTypeField = "";
            this.serverField = "";
            this.sourcetypeField = "";
            this.sourcekeyField = "";
            this.isendField = "";
            this.lable1Field = "";
            this.lable2Field = "";
            this.lable3Field = "";
            this.lable4Field = "";
            this.lable5Field = "";
            this.sourceLineNo1Field = "";
            this.sourceLineNo2Field = "";
            this.sourceLineNo3Field = "";
            this.sourceLineNo4Field = "";
            this.sourceLineNo5Field = "";
        }
        public string ProcName
        {
            get
            {
                return this.procNameField;
            }
            set
            {
                this.procNameField = value;
            }
        }
        public string sendDelimiter
        {
            get
            {
                return this.sendDelimiterField;
            }
            set
            {
                this.sendDelimiterField = value;
            }
        }
        public string ptcid
        {
            get
            {
                return this.ptcidField;
            }
            set
            {
                this.ptcidField = value;
            }
        }
        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }
        public string taskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }
        public string databasename
        {
            get
            {
                return this.databasenameField;
            }
            set
            {
                this.databasenameField = value;
            }
        }
        public string appflag
        {
            get
            {
                return this.appflagField;
            }
            set
            {
                this.appflagField = value;
            }
        }
        public string recordType
        {
            get
            {
                return this.recordTypeField;
            }
            set
            {
                this.recordTypeField = value;
            }
        }
        public string server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }
        public string type
        {
            get
            {
                return this.sourcetypeField;
            }
            set
            {
                this.sourcetypeField = value;
            }
        }
        public string sourcekey
        {
            get
            {
                return this.sourcekeyField;
            }
            set
            {
                this.sourcekeyField = value;
            }
        }
        public string elabel1
        {
            get
            {
                return this.lable1Field;
            }
            set
            {
                this.lable1Field = value;
            }
        }
        public string elabel2
        {
            get
            {
                return this.lable2Field;
            }
            set
            {
                this.lable2Field = value;
            }
        }
        public string elabel3
        {
            get
            {
                return this.lable3Field;
            }
            set
            {
                this.lable3Field = value;
            }
        }
        public string elabel4
        {
            get
            {
                return this.lable4Field;
            }
            set
            {
                this.lable4Field = value;
            }
        }
        public string elabel5
        {
            get
            {
                return this.lable5Field;
            }
            set
            {
                this.lable5Field = value;
            }
        }
        public string sourcelineno1
        {
            get
            {
                return this.sourceLineNo1Field;
            }
            set
            {
                this.sourceLineNo1Field = value;
            }
        }
        public string sourcelineno2
        {
            get
            {
                return this.sourceLineNo2Field;
            }
            set
            {
                this.sourceLineNo2Field = value;
            }
        }
        public string sourcelineno3
        {
            get
            {
                return this.sourceLineNo3Field;
            }
            set
            {
                this.sourceLineNo3Field = value;
            }
        }
        public string sourcelineno4
        {
            get
            {
                return this.sourceLineNo4Field;
            }
            set
            {
                this.sourceLineNo4Field = value;
            }
        }
        public string sourcelineno5
        {
            get
            {
                return this.sourceLineNo5Field;
            }
            set
            {
                this.sourceLineNo5Field = value;
            }
        }
        
    }
}
