// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>InfoWms.API</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.NSPRFOT08.Response
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Utility
    {

        private List<UtilityHeader> utilityHeaderField;

        [XmlElement("UtilityHeader")]
        public List<UtilityHeader> UtilityHeader
        {
            get
            {
                if ((this.utilityHeaderField == null))
                {
                    this.utilityHeaderField = new List<UtilityHeader>();
                }
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }

        #region Clone method
        /// <summary>
        /// Create a clone of this Utility object
        /// </summary>
        public virtual Utility Clone()
        {
            return ((Utility)(this.MemberwiseClone()));
        }
        #endregion
    }

    public partial class UtilityHeader
    {

        private string dATEFORMATField;

        private string field1Field;

        private string value1Field;

        private string dBAlias1Field;

        private string field2Field;

        private string value2Field;

        private string dBAlias2Field;

        private string field3Field;

        private string value3Field;

        private string dBAlias3Field;

        private string field4Field;

        private string value4Field;

        private string dBAlias4Field;

        private string field5Field;

        private string value5Field;

        private string dBAlias5Field;

        private string ScreenField;

        public string DATEFORMAT
        {
            get
            {
                return this.dATEFORMATField;
            }
            set
            {
                this.dATEFORMATField = value;
            }
        }

        public string Field1
        {
            get
            {
                return this.field1Field;
            }
            set
            {
                this.field1Field = value;
            }
        }

        public string Value1
        {
            get
            {
                return this.value1Field;
            }
            set
            {
                this.value1Field = value;
            }
        }

        public string DBAlias1
        {
            get
            {
                return this.dBAlias1Field;
            }
            set
            {
                this.dBAlias1Field = value;
            }
        }

        public string Field2
        {
            get
            {
                return this.field2Field;
            }
            set
            {
                this.field2Field = value;
            }
        }

        public string Value2
        {
            get
            {
                return this.value2Field;
            }
            set
            {
                this.value2Field = value;
            }
        }

        public string DBAlias2
        {
            get
            {
                return this.dBAlias2Field;
            }
            set
            {
                this.dBAlias2Field = value;
            }
        }

        public string Field3
        {
            get
            {
                return this.field3Field;
            }
            set
            {
                this.field3Field = value;
            }
        }

        public string Value3
        {
            get
            {
                return this.value3Field;
            }
            set
            {
                this.value3Field = value;
            }
        }

        public string DBAlias3
        {
            get
            {
                return this.dBAlias3Field;
            }
            set
            {
                this.dBAlias3Field = value;
            }
        }

        public string Field4
        {
            get
            {
                return this.field4Field;
            }
            set
            {
                this.field4Field = value;
            }
        }

        public string Value4
        {
            get
            {
                return this.value4Field;
            }
            set
            {
                this.value4Field = value;
            }
        }

        public string DBAlias4
        {
            get
            {
                return this.dBAlias4Field;
            }
            set
            {
                this.dBAlias4Field = value;
            }
        }

        public string Field5
        {
            get
            {
                return this.field5Field;
            }
            set
            {
                this.field5Field = value;
            }
        }

        public string Value5
        {
            get
            {
                return this.value5Field;
            }
            set
            {
                this.value5Field = value;
            }
        }

        public string DBAlias5
        {
            get
            {
                return this.dBAlias5Field;
            }
            set
            {
                this.dBAlias5Field = value;
            }
        }

        public string Screen
        {
            get { return this.ScreenField; }
            set{this.ScreenField=value;}
        }

        #region Clone method
        /// <summary>
        /// Create a clone of this UtilityUtilityHeader object
        /// </summary>
        public virtual UtilityHeader Clone()
        {
            return ((UtilityHeader)(this.MemberwiseClone()));
        }
        #endregion
    }
}
