// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.NSPRFTM01.Response</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.NSPRFFLRTRSKU01X.Response
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Utility
    {

        private List<UtilityHeader> utilityHeaderFields;
        public Utility()
        {
            utilityHeaderFields = new List<UtilityHeader>();
        }
        [System.Xml.Serialization.XmlElement("UtilityHeader")]
        public List<UtilityHeader> UtilityHeaders
        {
            get
            {

                return this.utilityHeaderFields;
            }
            set
            {
                this.utilityHeaderFields = value;
            }
        }
    }

    public partial class UtilityHeader
    {

        private string receiptkeyField;

        private string skuField;

        private string lottable02Field;

        private string notesField;

        private int qtyField;

        private int qcqtyField;

        private int wqcqtyField;

        private string linenoField;

        private string altskuField;

        private string susr3Field;

        private string statusField;

        private string errmsgField;

        private string rectypeField;

        private string rectotalField;

        public string ReceiptKey
        {
            get
            {
                return this.receiptkeyField;
            }
            set
            {
                this.receiptkeyField = value;
            }
        }

        public string Sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }

        public string lottable02
        {
            get
            {
                return this.lottable02Field;
            }
            set
            {
                this.lottable02Field = value;
            }
        }

        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        public int Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        public int qcqty
        {
            get
            {
                return this.qcqtyField;
            }
            set
            {
                this.qcqtyField = value;
            }
        }

        public int wqcqty
        {
            get
            {
                return this.wqcqtyField;
            }
            set
            {
                this.wqcqtyField = value;
            }
        }

        public string lineno
        {
            get
            {
                return this.linenoField;
            }
            set
            {
                this.linenoField = value;
            }
        }

        public string AltSku
        {
            get
            {
                return this.altskuField;
            }
            set
            {
                this.altskuField = value;
            }
        }

        public string SUsr3
        {
            get
            {
                return this.susr3Field;
            }
            set
            {
                this.susr3Field = value;
            }
        }

        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public string errmsg
        {
            get
            {
                return this.errmsgField;
            }
            set
            {
                this.errmsgField = value;
            }
        }

        public string rectype
        {
            get
            {
                return this.rectypeField;
            }
            set
            {
                this.rectypeField = value;
            }
        }

        public string rectotal
        {
            get
            {
                return this.rectotalField;
            }
            set
            {
                this.rectotalField = value;
            }
        }
    }

}
