// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace> RFDeviceAPP.Common.NSPRFTPA00.Request</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.NSPRFTPA00.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    

    public partial class Utility
    {
        public static Utility Create(string taskkey, string fromloc, params string[] args)
        {
            Utility utility = new Utility();
            utility.UtilityHeader.taskdetailkey = taskkey;
            utility.UtilityHeader.fromloc = fromloc;
            utility.UtilityHeader.fromid1 = args[0];
            utility.UtilityHeader.fromid2 = args[1];
            utility.UtilityHeader.fromid3 = args[2];
            utility.UtilityHeader.fromid4 = args[3];
            utility.UtilityHeader.fromid5 = args[4];

            return utility;
        }

        private UtilityHeader utilityHeaderField;

        public UtilityHeader UtilityHeader
        {
            get
            {
                if ((this.utilityHeaderField == null))
                {
                    this.utilityHeaderField = new UtilityHeader();
                }
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }
    }

    public partial class UtilityHeader
    {

        private string procNameField;

        private string sendDelimiterField;

        private string ptcidField;

        private string useridField;

        private string taskIdField;

        private string databasenameField;

        private string appflagField;

        private string recordTypeField;

        private string serverField;

        private string ttmField;

        private string taskdetailkeyField;

        private string fromlocField;

        private string fromid1Field;

        private string fromid2Field;

        private string fromid3Field;

        private string fromid4Field;

        private string fromid5Field;

        private string multiPalletRemainingField;

        private string area01Field;

        private string area02Field;

        private string area03Field;

        private string area04Field;

        private string area05Field;

        public UtilityHeader()
        {
            this.procNameField = "NSPRFTPA00";
            this.sendDelimiterField = "`";
            this.ptcidField = "";
            this.useridField = "";
            this.taskIdField = "";
            this.databasenameField = "";
            this.appflagField = "";
            this.recordTypeField = "";
            this.serverField = "";
            this.ttmField = "TTM";
            this.fromid2Field = "";
            this.fromid3Field = "";
            this.fromid4Field = "";
            this.fromid5Field = "";
            this.multiPalletRemainingField = "";
            this.area01Field = "";
            this.area02Field = "";
            this.area03Field = "";
            this.area04Field = "";
            this.area05Field = "";
        }

        public string ProcName
        {
            get
            {
                return this.procNameField;
            }
            set
            {
                this.procNameField = value;
            }
        }

        public string sendDelimiter
        {
            get
            {
                return this.sendDelimiterField;
            }
            set
            {
                this.sendDelimiterField = value;
            }
        }

        public string ptcid
        {
            get
            {
                return this.ptcidField;
            }
            set
            {
                this.ptcidField = value;
            }
        }

        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }

        public string taskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }

        public string databasename
        {
            get
            {
                return this.databasenameField;
            }
            set
            {
                this.databasenameField = value;
            }
        }

        public string appflag
        {
            get
            {
                return this.appflagField;
            }
            set
            {
                this.appflagField = value;
            }
        }

        public string recordType
        {
            get
            {
                return this.recordTypeField;
            }
            set
            {
                this.recordTypeField = value;
            }
        }

        public string server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }

        public string ttm
        {
            get
            {
                return this.ttmField;
            }
            set
            {
                this.ttmField = value;
            }
        }

        public string taskdetailkey
        {
            get
            {
                return this.taskdetailkeyField;
            }
            set
            {
                this.taskdetailkeyField = value;
            }
        }

        public string fromloc
        {
            get
            {
                return this.fromlocField;
            }
            set
            {
                this.fromlocField = value;
            }
        }

        public string fromid1
        {
            get
            {
                return this.fromid1Field;
            }
            set
            {
                this.fromid1Field = value;
            }
        }

        public string fromid2
        {
            get
            {
                return this.fromid2Field;
            }
            set
            {
                this.fromid2Field = value;
            }
        }

        public string fromid3
        {
            get
            {
                return this.fromid3Field;
            }
            set
            {
                this.fromid3Field = value;
            }
        }

        public string fromid4
        {
            get
            {
                return this.fromid4Field;
            }
            set
            {
                this.fromid4Field = value;
            }
        }

        public string fromid5
        {
            get
            {
                return this.fromid5Field;
            }
            set
            {
                this.fromid5Field = value;
            }
        }

        public string MultiPalletRemaining
        {
            get
            {
                return this.multiPalletRemainingField;
            }
            set
            {
                this.multiPalletRemainingField = value;
            }
        }

        public string area01
        {
            get
            {
                return this.area01Field;
            }
            set
            {
                this.area01Field = value;
            }
        }

        public string area02
        {
            get
            {
                return this.area02Field;
            }
            set
            {
                this.area02Field = value;
            }
        }

        public string area03
        {
            get
            {
                return this.area03Field;
            }
            set
            {
                this.area03Field = value;
            }
        }

        public string area04
        {
            get
            {
                return this.area04Field;
            }
            set
            {
                this.area04Field = value;
            }
        }

        public string area05
        {
            get
            {
                return this.area05Field;
            }
            set
            {
                this.area05Field = value;
            }
        }
    }
}
