// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace> RFDeviceAPP.Common.NSPRFTPA02.Response</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.NSPRFTPA02.Request
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


   

    public partial class Utility
    {
        public static Utility Create(string userid, string taskdetailkey, string fromloc, string fromid, string toloc, string toid, string qty, string packkey, string uom, string reason)
        {
            Utility utility = new Utility();
            utility.UtilityHeader.taskdetailkey=taskdetailkey;
            utility.UtilityHeader.fromid=fromid;
            utility.UtilityHeader.fromloc=fromloc;
            utility.UtilityHeader.packkey=packkey;
            utility.UtilityHeader.qty=qty;
            utility.UtilityHeader.toid=toid;
            utility.UtilityHeader.toloc=toloc;
            utility.UtilityHeader.uom=uom;
            utility.UtilityHeader.userid=userid;
            utility.UtilityHeader.reason = reason;

            return utility;
        }
        private UtilityHeader utilityHeaderField;

        public UtilityHeader UtilityHeader
        {
            get
            {
                if ((this.utilityHeaderField == null))
                {
                    this.utilityHeaderField = new UtilityHeader();
                }
                return this.utilityHeaderField;
            }
            set
            {
                this.utilityHeaderField = value;
            }
        }
    }

    public partial class UtilityHeader
    {

        private string procNameField;

        private string sendDelimiterField;

        private string ptcidField;

        private string useridField;

        private string taskIdField;

        private string databasenameField;

        private string appflagField;

        private string recordTypeField;

        private string serverField;

        private string ttmField;

        private string taskdetailkeyField;

        private string fromlocField;

        private string fromid_lblField;

        private string fromidField;

        private string tolocField;

        private string tochkdigitField;

        private string toidField;

        private string qtyField;

        private string packkeyField;

        private string uomField;

        private string reasonField;

        public UtilityHeader()
        {
            this.procNameField = "NSPRFTPA02";
            this.sendDelimiterField = "`";
            this.ptcidField = "";
            this.useridField = "sceadmin";
            this.taskIdField = "";
            this.databasenameField = "";
            this.appflagField = "";
            this.recordTypeField = "";
            this.serverField = "";
            this.ttmField = "TTM";
            this.taskdetailkeyField = "";
            this.fromlocField = "";
            this.fromid_lblField = "";
            this.fromidField = "";
            this.tolocField = "";
            this.tochkdigitField = "";
            this.toidField = "";
            this.qtyField = "";
            this.packkeyField = "";
            this.uomField = "EA";
            this.reasonField = "";
        }

        public string ProcName
        {
            get
            {
                return this.procNameField;
            }
            set
            {
                this.procNameField = value;
            }
        }

        public string sendDelimiter
        {
            get
            {
                return this.sendDelimiterField;
            }
            set
            {
                this.sendDelimiterField = value;
            }
        }

        public string ptcid
        {
            get
            {
                return this.ptcidField;
            }
            set
            {
                this.ptcidField = value;
            }
        }

        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }

        public string taskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }

        public string databasename
        {
            get
            {
                return this.databasenameField;
            }
            set
            {
                this.databasenameField = value;
            }
        }

        public string appflag
        {
            get
            {
                return this.appflagField;
            }
            set
            {
                this.appflagField = value;
            }
        }

        public string recordType
        {
            get
            {
                return this.recordTypeField;
            }
            set
            {
                this.recordTypeField = value;
            }
        }

        public string server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }

        public string ttm
        {
            get
            {
                return this.ttmField;
            }
            set
            {
                this.ttmField = value;
            }
        }

        public string taskdetailkey
        {
            get
            {
                return this.taskdetailkeyField;
            }
            set
            {
                this.taskdetailkeyField = value;
            }
        }

        public string fromloc
        {
            get
            {
                return this.fromlocField;
            }
            set
            {
                this.fromlocField = value;
            }
        }

        public string fromid_lbl
        {
            get
            {
                return this.fromid_lblField;
            }
            set
            {
                this.fromid_lblField = value;
            }
        }

        public string fromid
        {
            get
            {
                return this.fromidField;
            }
            set
            {
                this.fromidField = value;
            }
        }

        public string toloc
        {
            get
            {
                return this.tolocField;
            }
            set
            {
                this.tolocField = value;
            }
        }

        public string tochkdigit
        {
            get
            {
                return this.tochkdigitField;
            }
            set
            {
                this.tochkdigitField = value;
            }
        }

        public string toid
        {
            get
            {
                return this.toidField;
            }
            set
            {
                this.toidField = value;
            }
        }

        public string qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        public string packkey
        {
            get
            {
                return this.packkeyField;
            }
            set
            {
                this.packkeyField = value;
            }
        }

        public string uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
    }
}
