// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>RFDeviceAPP.Common.NSPRFTM01.Response</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace RFDeviceAPP.Common.TaskReason.Response
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class TaskReason
    {

        private List<TaskReasonHeader> taskHeaderField;

        public TaskReason()
        {
            this.taskHeaderField = new List<TaskReasonHeader>();
        }

        //[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        //[System.Xml.Serialization.XmlArrayItemAttribute("AdvancedShipNoticeHeader", IsNullable = false)]
        [System.Xml.Serialization.XmlElement("TaskReasonHeader")]
        public List<TaskReasonHeader> TaskReasonHeaders
        {
            get
            {
                return this.taskHeaderField;
            }
            set
            {
                this.taskHeaderField = value;
            }
        }
    }

    public partial class TaskReasonHeader
    {

        private string serialKeyField;

        private string whseIdField;

        private string TASKMANAGERREASONKEYField;

        private string DescrField;

       

        private string addDateField;

        private string addWhoField;

        private string editDateField;

        private string editWhoField;

        private string doorField;

        private string routeField;

        private string stopField;

        private string putawayZoneField;

        public string SerialKey
        {
            get
            {
                return this.serialKeyField;
            }
            set
            {
                this.serialKeyField = value;
            }
        }

        public string WhseId
        {
            get
            {
                return this.whseIdField;
            }
            set
            {
                this.whseIdField = value;
            }
        }

        public string TASKMANAGERREASONKEY
        {
            get
            {
                return this.TASKMANAGERREASONKEYField;
            }
            set
            {
                this.TASKMANAGERREASONKEYField = value;
            }
        }

        public string Descr
        {
            get
            {
                return this.DescrField;
            }
            set
            {
                this.DescrField = value;
            }
        }

       

        public string AddDate
        {
            get
            {
                return this.addDateField;
            }
            set
            {
                this.addDateField = value;
            }
        }

        public string AddWho
        {
            get
            {
                return this.addWhoField;
            }
            set
            {
                this.addWhoField = value;
            }
        }

        public string EditDate
        {
            get
            {
                return this.editDateField;
            }
            set
            {
                this.editDateField = value;
            }
        }

        public string EditWho
        {
            get
            {
                return this.editWhoField;
            }
            set
            {
                this.editWhoField = value;
            }
        }

        public string Door
        {
            get
            {
                return this.doorField;
            }
            set
            {
                this.doorField = value;
            }
        }

        public string Route
        {
            get
            {
                return this.routeField;
            }
            set
            {
                this.routeField = value;
            }
        }

        public string Stop
        {
            get
            {
                return this.stopField;
            }
            set
            {
                this.stopField = value;
            }
        }

        public string PutawayZone
        {
            get
            {
                return this.putawayZoneField;
            }
            set
            {
                this.putawayZoneField = value;
            }
        }
    }

}
